### ISSUE TITLE
Graph doesn't take up full width

### ISSUE THREAD

**Issue by billyjacoby** [tradingview/lightweight-charts#1015]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

Display an area chart with few points of data. When only supplying 2 data points, I would expect the graph to still span the width of it's container without space on either side, however instead it seems that the graph adds a margin to each side.

**Actual behavior:**
When there are fewer than about 15 points plotted the graph has large margins on both the left and right.

**Expected behavior:**
After calling the `timeScale().fitContent()` function, the graph should take up all available horizontal space.

**Screenshots:**
![Screen Shot 2022-02-15 at 3 38 36 PM](https://user-images.githubusercontent.com/27246508/154145265-2264bb7d-65fd-464e-a636-1402a2e382aa.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Well, this is by design if you're going to display [less bars that 2](https://github.com/tradingview/lightweight-charts/blob/c854615204bc682f05df7a7053f4b31e997c11d3/src/model/time-scale.ts#L36) (this is our current limitation for min amount of bars).

As for the 2 points, it should work but the time scale knows nothing about the actual spacing of each series type (a line and a candlestick bars have different widths) that's why it fits for exact logical indexes. Instead of you could use the trick like the following:

```js
chart.timeScale().setVisibleLogicalRange({ from: 0.5, to: data.length - 1.5 });
```

to set "exact" visible range for your _line chart_ only.
