### ISSUE TITLE
Display the largest orders in OrderBook in a meaningful way

### ISSUE THREAD

**Issue by CRY-D** [tradingview/lightweight-charts#1063]
Hi.
First, I want to mention that the way that all exchanges present or visualize orderbook is completely useless.

![Screenshot 2022-04-16 at 22-06-51 40333 34 BTCUSDT Binance Spot](https://user-images.githubusercontent.com/16564491/163691399-48f08603-4a39-4a2e-90a6-8d45b6e60d5a.png)

I would try to begin by putting in perspective what I try to do, so I want, is to represent large orders in somehow useful way.
And for that I fetch the real-time data from binance exchange, and it shows the large orders using lines, and the width of lines depends on data (asks and bids) received from binance.
The screenshot below explains better what I've done.

![Screenshot 2022-04-16 at 22-14-47 GRID-BOT Home](https://user-images.githubusercontent.com/16564491/163691833-f2afe90c-9373-42b8-96ef-609451ef08ee.png)

I was thinking, or what I want to ask is whether there was any way to represent it in something like heatmap ?
Something like so.

![Screenshot 2022-04-16 at 22-36-07 TensorCharts com](https://user-images.githubusercontent.com/16564491/163692073-000b4342-5fe3-41b5-ac99-dd44f628aef9.png)

**Comment by SlicedSilver** [comment]
That chart is a great idea. 👍

However, it's not possible to do a heat map within Lightweight charts at the moment, and I believe that this would be out of scope for the project.

**Comment by jaycee11** [comment]
Hey CRY-D could you hit me up in telegram https://t.me/CryptoPowerX, would like to ask you something.

**Comment by alaeddineelmouets** [comment]
hello my friend, can you send me the pine script for tradingview that fetch the real-time data from binance exchange, and it shows the large orders using lines

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples (see above links):
- Heatmap series
- Rectangle Drawing Tool

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.

**Comment by frankmazon** [comment]
can i get the source code
