### ISSUE TITLE
fitContent() leaves empty space for hidden series

### ISSUE THREAD

**Issue by Biszu** [tradingview/lightweight-charts#1151]
**Lightweight Charts Version:**
3.8.0 and the current dev version of 4.0.0

**Steps/code to reproduce:**
1. Add two series, one visible with fewer data points, second invisible but with many more data points
2. call chart.timeScale().fitContent()

**Actual behavior:**
There is lots of empty space on the left side of the chart.

**Expected behavior:**
Visible content takes the full width of the chart, with no empty space.

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/264wrdzL/

**Comment by SlicedSilver** [comment]
That is the expected behaviour for `fitContent`.

**From the docs:**

> Automatically calculates the visible range to fit all data from all series.

https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#fitcontent

You can use the `setVisibleRange` and `setVisibleLogicalRange` apis to control the visible range manually.
* https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#setvisiblelogicalrange
* https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#setvisiblerange

In your JSFiddle example, you can set the visible range using the first and last date values for the visible data set.
```js
// chart.timeScale().setVisibleRange({from: data[0].time, to: data[data.length - 1].time});
chart.timeScale().setVisibleRange({from: '2019-02-28', to: '2019-05-28'});
```
