### ISSUE TITLE
last value label not shown if chart instance is assigned to vue ref

### ISSUE THREAD

**Issue by mwahlhuetter** [tradingview/lightweight-charts#1161]
**Lightweight Charts Version:** 3.8.0

**Steps/code to reproduce:**

Create a chart and assign the instance to a vue ref/reactive variable, then add any series to it.

**Actual behavior:**

The label indicating the last value is not displayed.

**Expected behavior:**

The label indicating the last value is displayed.

**CodeSandbox/JSFiddle/etc link:**
[https://codesandbox.io/s/vue-lightweight-charts-last-value-bug-z2elgk](https://codesandbox.io/s/vue-lightweight-charts-last-value-bug-z2elgk)

**Comment by SlicedSilver** [comment]
**Disclaimer:** I'm not very experienced with Vue so this may not be the complete answer.

The example you provided seems to work correctly if we rather use `shallowRef` instead of `ref`. 

Looking at the [Vue documentation](https://vuejs.org/api/reactivity-core.html#ref), it seems that `ref` modifies the value to make it deeply reactive which is probably not fully compatible with lightweight charts: 

> "If an object is assigned as a ref's value, the object is made deeply reactive with [reactive()](https://vuejs.org/api/reactivity-core.html#reactive)."

`shallowRef` doesn't do this deep conversion, and this seems to resolve your issue.

**Comment by mwahlhuetter** [comment]
Thank you so much, that really did solve my issue!
I just had to also assign the series instance to a `shallowRef` in order for my use case to finally work.
