### ISSUE TITLE
How to enable debug mode.

### ISSUE THREAD

**Issue by Cass0wary** [tradingview/lightweight-charts#1176]
I am hitting the issue `lightweight-charts Uncaught Error: Value is null`  running version `"lightweight-charts": "^3.8.0",` installed via 

![image](https://user-images.githubusercontent.com/14795613/195064576-e073b388-e884-42ad-8d20-754cd8cf2073.png)

After reading through a heap of the other issues I am pretty sure it is due to one of the following reasons:
- some of the data is null
- potential duplication on data in timestamp
- `time` should be ordered by time in ASC order

The last one I am doing like so:

```
const sortedAsc = data3.sort(
              (objA, objB) => Number(objA.time) - Number(objB.time),
            );
```

Now I have also read that I can get better error messages by running in `DEBUG` mode, but I can't for the life of me work out how to enable DEBUG mode. I couldn't find any search results for `DBEUG` in the docs.

I have [installed via](https://tradingview.github.io/lightweight-charts/docs0 `npm install --save lightweight-charts` Is there a flag I can set in my code, or a different package I install?

**Comment by SlicedSilver** [comment]
Firstly, I think your error is related to the `time` values within your data. They appear to be too large. The expected value should be **seconds** since epoch instead of milliseconds, thus you should divide that number by a 1000. (https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp)

As you mentioned, data points should be passed in ascending order (newest values at the end), and there shouldn't be any data points which share a `time` value (no duplicate times).

You can set the `NODE_ENV` environment variable to anything besides `production` and it should load the development version. If you are using a `module` version of node then that may not work, but you could always go into `node_modules/lightweight-charts/package.json` and temporarily change the `"module"` value.

If you are using the standalone version then use `lightweight-charts.standalone.development.js` instead of `lightweight-charts.standalone.production.js`.

One of the benefits of using the development version is that the console messages will make a bit more sense since the call stack names won't be minified anymore.

**Comment by Cass0wary** [comment]
Thanks @SlicedSilver for getting back to me so fast... the below worked a treat for me. I should have searched for development 🤦 

> but you could always go into node_modules/lightweight-charts/package.json and temporarily change the "module" value.

Also thanks for the heads up on the seconds since epoch instead of milliseconds.
