### ISSUE TITLE
Price scale is not visible if data values below 1

### ISSUE THREAD

**Issue by nick-dolan** [tradingview/lightweight-charts#1186]
**Lightweight Charts Version:**  3.8.0

**Steps/code to reproduce:**

If data has small values there is no scale to be appear.

```
lineSeries.setData([
  {
    value: 0.4563,
    time: 1666605600
  },
  {
    value: 0.4572,
    time: 1666606500
  },
  ...
])
```

**Screenshots:**

<img width="609" alt="image" src="https://user-images.githubusercontent.com/25667028/197760523-328f3dc1-2a5c-48b0-82c1-84cc97534deb.png">

**Expected behavior:**

D3 chart with the same data looks ok.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/25667028/197760850-fbece407-25c6-4335-b5ce-6d13e7a6e814.png">

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/nickdolan/oc6fxgq1/8/

**Comment by SlicedSilver** [comment]
The price scale isn't showing more tick marks because the precision of the price values is smaller than the expected (default) `minmove` value for the price formatter.

You can change the `precision` and `minmove` values for a series by setting the `priceFormat ` option.

For example, with your code:
```js
const lineSeries1 = chart.addLineSeries({
  lineWidth: 2,
  priceScaleId: 'left',
  color: '#1DA1F2',
  priceLineVisible: false,
  crosshairMarkerVisible: true,
  lastValueVisible: true,
  // ADDED priceFormat...
  priceFormat: {
    type: 'price', precision: 3, minMove: 0.001
  }
})
``` 

Here are the relevant docs:

- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn

**Comment by nick-dolan** [comment]
Thanks!
