### ISSUE TITLE
.fitContent() doesn’t work with lower amount of data points

### ISSUE THREAD

**Issue by chromale** [tradingview/lightweight-charts#1200]
**Describe the bug**
When there is lower amount of datapoints the `.fitContent()` method doesn’t work as expected. Creating margins on sides of charts. 

**To Reproduce**
Use any LightWeight chart with `.fitContent()`  and lower amount od datapoints:
https://jsfiddle.net/ew40o9s8/1/

**Expected behavior**
I don’t know how many data points will go into charts so I need auto-fit the content correctly. I expect the `.fitContent()` should handle these situations. 

**Screenshots**
![CleanShot 2022-11-18 at 20 43 01@2x](https://user-images.githubusercontent.com/10242446/202790085-30073aa7-a23f-4209-b3f7-d922c32d52b1.png)

**Additional context**
Example is based on official demo: https://jsfiddle.net/TradingView/4pd5j8xa/
Version used: 3.8.0

**Comment by SlicedSilver** [comment]
The [time scale](https://tradingview.github.io/lightweight-charts/docs/time-scale) will include half a bar width on each side of the content when using fitContent on a line series. The reasoning behind this relates to the different series types which can be plotted, and where within the bar width the data point is plotted. In this case, a line series draws the line to the centre of the bar width while a candle would take up more horizontal space. The candle needs this 'space' so that it fits entirely on the screen.

If you are only plotting a line series (or similar) then you could use the [`setVisibleLogicalRange`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#setvisiblelogicalrange) with a `from` value equal to 0.5 and a `to` value equal to the length of the data set minus 0.5.

```javascript
// dataset consists of 100 points
chart.timeScale().setVisibleLogicalRange({ from: 0.5, to: 99.5 })
```
