### ISSUE TITLE
Passing a freezed dataset causes error "cannot add property w_, object is not extensible"

### ISSUE THREAD

**Issue by juansalvatore** [tradingview/lightweight-charts#1229]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

```js
interface Data {
  time: Time;
  value: number;
}

const data: Data = [...]

const freezedData = deepFreeze(data);

areaSeries.setDate(freezedData); // Error: cannot add property w_, object is not extensible
```

**Actual behavior:**

areaSeries.setData relies on passing an array of mutable objects. 

**Expected behavior:**

If using redux or needing to use a dataset that is immutable I would expect the library to do a deep copy or make it more explicit that the data is mutated.

**Screenshots:**

![image](https://user-images.githubusercontent.com/11010928/209395451-39c52ad8-428e-4db0-a2fa-2630b45070c6.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by SlicedSilver** [comment]
This is the expected behaviour of the library. You need to pass the data as a mutable array.

**Comment by astriskit** [comment]
@SlicedSilver - Would it be possible to provide an opt-out for this. 

Use-case - using redux-toolkit which has by design the immutability added to it - so when using the updates through the store - updating/adding values through the `setData` api becomes just impossible. That makes redux-toolkit - a very popular state-management-system not work with another very nice library i.e the lightweight-charts.

Thanks.

**Comment by SlicedSilver** [comment]
@astriskit We don't have any plans to change this behaviour, or add an opt-out for it.

The solution you found is what I would suggest. Cloning the data before passing it to the library will mean that the library can freely modify the data without it affecting the redux data. 

For LWC, it is more performant to use the current approach of modifying the data objects instead of cloning internally, or creating additional maps for this extra calculated information for each data point.

- [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) with a fallback to `JSON.parse(JSON.stringify(data))` would probably be the most performant way to clone the data at the moment.

**Comment by Jokero** [comment]
@SlicedSilver I also found this very confusing when tried to figure out why my React component re-renders every time I call `series.update(...)` and pass same unchanged candlestick that I receive from HTTP API. 

Is this **unexpected** behaviour documented somewhere on https://tradingview.github.io/lightweight-charts/docs? I haven't found any mentions of mutability there

**Comment by SlicedSilver** [comment]
React shouldn't need to re-render if you are just calling the `series.update()` method since none of the DOM will change. You should get better performance if you can call series.update in such a way that React doesn't think it needs to re-render.

I don't think it is specifically mentioned anywhere that the data can be mutated but the types (defined in typescript) don't mention the `readonly` keyword so we aren't specifically saying that it is expected that the objects won't be mutated. **It would be better if we specifically mentioned that it can be mutated.**

**Comment by Jokero** [comment]
@SlicedSilver In my case I just pass `seriesUpdates` as a prop to a chart component and use `useEffect` to apply it to existing series (`series.update(...)`) when it's modified. 

`seriesUpdates` is fetched by React Query and changes only when new (updated) data are returned. Since `lightweight-charts` modifies items of `seriesUpdates`, every request for series updates results in a new `seriesUpdates` and this causes component re-render. Workaround here is to wrap `seriesUpdates` in `structuredClone` in the chart component as you suggested above.

> It would be better if we specifically mentioned that it can be mutated

That would be very appreciated
