### ISSUE TITLE
Markers series

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#127]
In #24 we'll implement series-based markers (attached to series), but it would be awesome to have a series with events, where we can set price where marker should be placed on the chart. Also, these markers might be "in the future" (extend time scale).

See comments:
- https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-511904914
- https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-511949905
- https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-512041090
- https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-512154205

**Comment by HighBreedTech** [comment]
Hi if this could be implemented on a realtime data it will be nice adding a price marker and also line included i think PriceLine + Anotation will be good eg: priceline + label and the label alignment can be set to Right, Left, Center, Up, Down of the line this  could be good.
![WhatsApp Image 2020-02-18 at 3 22 47 PM](https://user-images.githubusercontent.com/21047633/75152776-1e6d7200-570a-11ea-8b50-02b768d4982c.jpeg)

**Comment by canselcik** [comment]
This would be great. What kind of proposal does this need? Proposal for the API design or how it would be implemented in the library internals?

**Comment by timocov** [comment]
API and behavioural, how it should look like, what methods/options should be added to manipulate, etc.

**Comment by Usey95** [comment]
🙋‍♂️ Here's my suggestion:
1、an option to turn on/off priceLine(maybe from point to priceScale Axis or something)
2、new 'image' shape with width/height/image source attributes or just add a new ImageMarker type which can be used to "setMarkers" as well.

**Comment by sadburai** [comment]
hi, is there already an update on this issue? I also think it would be great to draw the marker at an exact price, not just above or below the bar.

**Comment by michael-soorys** [comment]
Hi, this would be an awesome addition, currently in order to display a historical event on the chart you'd need to draw a shape, but setting a mark would be a better approach since some text information can be accessed on hover.

Is there any updates on the progress of this issue?

**Comment by timocov** [comment]
@sadburai @michael-soorys @canselcik can you guys put your 👍 to the first message of issue instead of posting a message please? It would be much better for everybody. Thank you!

**Comment by h0wXD** [comment]
If anyone's interested in this feature, I've added support for specifying exact value in a commit on my repo https://github.com/h0wXD/lightweight-charts/commit/f95891c21f8fefe36ab56d8117897f23c6756f76 , but I'm not sure if the firstValue parameter is correct. Works for me though:
![image](https://user-images.githubusercontent.com/10574115/121402706-ce610000-c98c-11eb-9d33-6db5c0b74888.png)

**Comment by jonluca** [comment]
Proposal:

Add a new `SeriesMarkerShape` called `line`

```
export type SeriesMarkerShape =	"circle" | "square"	| "arrowUp" | "arrowDown" | "line";
```

This would render like so:

![image](https://user-images.githubusercontent.com/13029040/148807405-27ad2163-38c8-411c-b783-dcee07f3165a.png)

**Comment by Gmexican14** [comment]
Interested to see if there have been any more developments for this issue, or are we still looking for a proper proposal to be presented? Very interested to have this implemented as currently it is the only reason why I have put off migrating to using lightweight-charts.

My main vision on how this works would be similar to plotting out a simple line series declaring: `{ time: '2022-07-05', value: 46.33 }` for the `x and y` values.

This would then plot out the location of the marker, possibly utilizing the existing `time` property. Since it seems that we are able to declare a location (e.g. above, below or in a bar), I'm curious on the work needed to have the flexibility to declare the Y value.

**Comment by movy** [comment]
I needed to mark entry-exit points along the candle, and basic trick is to create an invisible indicator with  `addLineSeries` where times equal to candle times (as always) and values equal to price levels you need your markers at.  Then simplt add markers to this __indicator__  series (not candle series!) with ` position: 'inBar'` -- markers will be plotted at exact value levels inside respective candles. Example:

![image](https://user-images.githubusercontent.com/4336560/193457391-104d9471-18f1-40d4-be2e-8342e580e3ce.png)

**Comment by muyen1** [comment]
> If anyone's interested in this feature, I've added support for specifying exact value in a commit on my repo [h0wXD@f95891c](https://github.com/h0wXD/lightweight-charts/commit/f95891c21f8fefe36ab56d8117897f23c6756f76) , but I'm not sure if the firstValue parameter is correct. Works for me though: ![image](https://user-images.githubusercontent.com/10574115/121402706-ce610000-c98c-11eb-9d33-6db5c0b74888.png)

Great feature i would love to implement it in my code. Could you show me how you connected two markers with dotted lines?

**Comment by Cass0wary** [comment]
Hey @fillky do you have any example and maybe a screenshot?

**Comment by fillky** [comment]
Yes sure, I've created this [example](https://jsfiddle.net/fillky/mnu9ckvL/59) for you.

**Comment by h0wXD** [comment]
> > If anyone's interested in this feature, I've added support for specifying exact value in a commit on my repo [h0wXD@f95891c](https://github.com/h0wXD/lightweight-charts/commit/f95891c21f8fefe36ab56d8117897f23c6756f76) , but I'm not sure if the firstValue parameter is correct. Works for me though: ![image](https://user-images.githubusercontent.com/10574115/121402706-ce610000-c98c-11eb-9d33-6db5c0b74888.png)
> 
> Great feature i would love to implement it in my code. Could you show me how you connected two markers with dotted lines?

@muyen1 I've had to add some [custom code](https://github.com/tradingview/lightweight-charts/compare/master...h0wXD:lightweight-charts:master) to add a WithGaps line type, although my code is quite out of date by now. Basically it allows for adding series for Stops, Targets, Orders with options lineStyle = LineStyle.LargeDashed and lineType = LineType.WithGaps, where I push null as value which I don't want rendered

**Comment by muyen1** [comment]
> 



> 

Hey, im willing to update your code for you if you are willling to allow me to use your fork. I'd like to keep this feature up to date

**Comment by dpmango** [comment]
> Proposal:
> 
> Add a new `SeriesMarkerShape` called `line`
> 
> ```
> export type SeriesMarkerShape =	"circle" | "square"	| "arrowUp" | "arrowDown" | "line";
> ```
> 
> This would render like so:
> 
> ![image](https://user-images.githubusercontent.com/13029040/148807405-27ad2163-38c8-411c-b783-dcee07f3165a.png)
> 
> This would respect both `size` and `lineStyle`, like the actual series lines. This could be dashed, solid, etc, with color and widths.

+1 for the 'line' implementation or support of custom shapes

**Comment by Obiwanbde** [comment]
Hi,
Is there a way to specify innerHtml for marker text ? I need to specify different font sizes for marker text lines and box like visual for marker frame ? ie:

Buy @ 3.21   bigger font and color1
Rule 2           smaller font and color2
Buy# 3          smaller font and color2

**Comment by Obiwanbde** [comment]
Hi,
For the bigger charts, it would be a good option to specify the text font size of marker at least. If I'm right, there is no way to do this now ?

**Comment by Elliott-Green** [comment]
+1 Give us lines

**Comment by fillky** [comment]
> Is there any way to set markers on a lineSeries?

See this example line 43 https://jsfiddle.net/fillky/mnu9ckvL/59

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following example:
	•	[Expiring Price Alerts](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/expiring-price-alerts): This example demonstrates how to draw markers on the chart (and into the future). [Demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/expiring-price-alerts/example/)

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.

**Comment by StayFoolisj** [comment]
> Yes sure, I've created this [example](https://jsfiddle.net/fillky/mnu9ckvL/59) for you.

Thanks for this, works great!
