### ISSUE TITLE
subscribeCrosshairMove gets triggered when series is updated?

### ISSUE THREAD

**Issue by Vimiso** [tradingview/lightweight-charts#1273]
It would seem when subscribing to crosshair move (`subscribeCrosshairMove`) it gets triggered when a candle series gets updated? Is this the expected behaviour?

Basically, I'm rendering tooltips when hovering over candles, I want to avoid re-rending a tooltip if the series arbitrarily updates. I guess it would be useful if the current candle you are hovered over is indeed the latest candle which has been updated, but otherwise seems unnecessary?

If this is the intended behavior could somebody offer any pointers on how to avoid doing things given an update?

Thanks

**Comment by SlicedSilver** [comment]
The event for `subscribeCrosshairMove` will only fire if the cursor is currently hovering over the chart. 
When an update occurs on the chart, it is the expected behaviour that the event will fire even if the crosshair is still over the same data point.

Within the event handler you could check if the data point is for the same point as the last time you updated the tooltip, and if it is then don't update the tooltip.

**Comment by Vimiso** [comment]
Thanks for clarifying. Yep, am going to cache the position so that I can ignore an update event if not currently hover over the position.
