### ISSUE TITLE
is it possible to add an animation of a smooth change in the position of the candle?

### ISSUE THREAD

**Issue by OlegLenskiy** [tradingview/lightweight-charts#1278]
is it possible to add an animation of a smooth change in the position of the candle for function **candleSeries.update** ?

**Comment by SlicedSilver** [comment]
Could you please provide more details of what you would like to see? What exactly do you mean by "change in the position of the candle"?

Are you talking out the scrolling of the time scale to bring the new candle into view? or would you like the candle itself to be animated in some way?

**Comment by OlegLenskiy** [comment]
https://user-images.githubusercontent.com/105483216/219876412-bee9a3ed-771d-42a5-be91-61e76bb04f80.mov

Please watch the video I have attached. It shows that when the data on the chart is updated, the candles move very sharply. Can this be done more smoothly, add a smooth effect?

> Could you please provide more details of what you would like to see? What exactly do you mean by "change in the position of the candle"?
> 
> Are you talking out the scrolling of the time scale to bring the new candle into view? or would you like the candle itself to be animated in some way?

**Comment by SlicedSilver** [comment]
There isn't a built-in way to smooth the price movements, and I doubt it will be added to the library because generally you want the data to updated as fast as possible.

You could add these animations yourself by repeatedly calling the `update` method with smaller changes than the actual change.

For example if you has this as your current bar: `open: 10, high: 12, low: 9, close: 10`
and the next update is `open: 10, high: 12, low: 9, close: 11` (close changing from `10 to 11`).

and you would like to animate the movement over ten frames then you could do ten smaller updates once per frame:
update 1: `open: 10, high: 12, low: 9, close: 10.1`
update 2: `open: 10, high: 12, low: 9, close: 10.2`
...
update 9: `open: 10, high: 12, low: 9, close: 10.9`
update 10: `open: 10, high: 12, low: 9, close: 11`

The candle will then appear to "animate" the change.

You would generally call `update()` and then using `requestAnimationFrame()` to schedule the next `update()` and so on...

**Comment by 0x0tyy** [comment]
> Please watch the video I have attached. It shows that when the data on the chart is updated, the candles move very sharply. Can this be done more smoothly, add a smooth effect?
> 
> > Could you please provide more details of what you would like to see? What exactly do you mean by "change in the position of the candle"?
> > Are you talking out the scrolling of the time scale to bring the new candle into view? or would you like the candle itself to be animated in some way?

imagine how this animation would look during times of high volatility.
if animation transition is around 50ms and there are huge price swings within that time period, animation frame would take longer to finish before accepting new data to start a new animation frame. i've been experiementing with animation in my fork and i think there is a huge subjective component. e.g. if it looks good to the user.

your thoughts?

**Comment by SlicedSilver** [comment]
I don't think that animation of candlestick prices will be added to the library because displaying the most up to date price data as possible is more important in our opinion.
As you mentioned, it would be difficult to correctly do animations if you are unsure when the next update will arrive. The animation needs a duration, so you need to guess ahead of time how long it will be until the next update arrives so you can set how long the animation should be.

Adding this type of animation (and handling all the edge cases of when the price changes again during an animation) could be handled externally to the library by using the `.update()` method on the series to provide the latest prices. As I discussed in my previous comment. 

If a feature can be achieved already using our API when we would be far less likely to add it to the library since one of the core goals of the library is to be small in bundle size.
