### ISSUE TITLE
Support the second price axis

### ISSUE THREAD

**Issue by kobermeit** [tradingview/lightweight-charts#129]
**Is your feature request related to a problem? Please describe.**

I'm drawing multiple line series and a candlestick series on a chart. I can see the price axis on the right, but I can't see the axis for the other series, which makes it hard to read. With my old ecahrts library, I had 3 axis on the chart (2 on the left, 1 on the right).

**Describe the solution you'd like**
Ability to set something like "showAxis: true" on each series and then configure if its on the left or right.

**Additional context**

Below is a screenshot of the current chart I have in eCharts. This is live and working, but I prefer the lightweight TV chart as the scrolling is far smoother than eCharts.

![image](https://user-images.githubusercontent.com/13191327/61395886-78fd4080-a894-11e9-96fe-6e642ff5ef5d.png)

**Comment by timocov** [comment]
Did you see other our products to display charts https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/ ? There is "Technical Analysis Charts" and there is such feature (demo https://charting-library.tradingview.com/).

We don't plan to add them to lightweight-charts yet.

**Comment by kobermeit** [comment]
@timocov Thanks, I actually have that TV charting library and currently using it in my product in another section. I just wanted to use lightweight for this chart instead and was hoping it would support this. But if the best solution is to use the full chart library, then that's fine :)

**Comment by timocov** [comment]
We want to keep lightweight-charts library lightweight 😉. Multiple axis feature is epic for the library and would add a lot of code and would increase the size of the lightweight-charts. Thus, unfortunately, I'm going to close this issue.

**Comment by Tucsky** [comment]
@timocov what about creating two "overlay series" on the same axis ? without showing that axis on the side, would that fit in the lightweight vision?

Exemple : I have a the price serie, sma, and 3 overlay series, I want to scale thoses 3 series on the same SCALE otherwise seeing them overlapping each other based on their respective range makes very low sense imo.
![image](https://user-images.githubusercontent.com/5738336/61999609-ada79e00-b0c5-11e9-8bca-28c009bfe116.png)

**Comment by timocov** [comment]
> without showing that axis on the side, would that fit in the lightweight vision?

If I understand you correctly this is already done in the lightweight-charts.

**Comment by Tucsky** [comment]
@timocov Well thats would be great, I do hope Im just missing a setting here :)

Let me try explain again: In other word thoses 3 volume series below aren't "locked" in the same volume scale (which actually makes sense because I neved told lightweight-chart to do so), I just called addLineSeries or addBarSeries without telling the chart to create those 3 on the same scale (*that* setting im looking for)

![scaleissue](https://user-images.githubusercontent.com/5738336/62281351-e8a32c00-b44d-11e9-8c7a-f173338d0da3.png)

The green line shouldn't go above the red or red above green as I pan left or right because the top / bottom of the visible point changed

**Comment by kirchet** [comment]
@Tucsky, for now, there is no way to add an ovelay series to the same scale as other overlay series. Probably we should add this possibility.

**Comment by Tucsky** [comment]
@kirchet thank you for considering it! Im gonna wait patiently.
Thats an awesome lib really, keeping it simple is what makes it so fast and accessible, but thats the only downside ive seen so I had to try :)

**Comment by timocov** [comment]
Good news everyone! We decided to add possibility to add the second price axis to the chart. If you have some specific requests for that until it isn't in the production - feel free to post your thought here.
