### ISSUE TITLE
Wrong timezone offset for Asia/Tehran

### ISSUE THREAD

**Issue by sadeghi-aa** [tradingview/lightweight-charts#1314]
**Lightweight Charts™ Version:** All versions (Also all versions of other TradingView charts)

**Steps/code to reproduce:**

Change the timezone to (UTC+04:30) Tehran in a TradingView chart.

**Actual behavior:**

The timezone is changed and as a result, 4 hours and 30 minutes are added to all times.

**Expected behavior:**

Recently, the timezone for Iran [has changed](https://www.timeanddate.com/time/change/iran/tehran#:~:text=Iran%20currently%20observes%20Iran%20Standard,was%20on%20September%2021%2C%202022.) and it doesn't observe DST anymore. So it should be UTC+03:30.

**Comment by SlicedSilver** [comment]
Closing this issue as it isn't directly related to Lightweight Charts. I'll notify the relevant team within TradingView regarding this issue.

**Comment by sadeghi-aa** [comment]
Thank you. I didn't exactly know where I should post it. For future reference, what is the correct repo to report such issues?

**Comment by SlicedSilver** [comment]
If you have access to the [charting-library repo](https://github.com/tradingview/charting_library/) then you could post a bug report there, but in general if it is an issue which is affecting the charts on tradingview.com then the [support page](https://www.tradingview.com/support/) would be a good place to start.

In this case, [Lightweight Charts doesn't actually handle timezones itself](https://tradingview.github.io/lightweight-charts/docs/time-zones) which is why I closed this issue. 

We appreciate you bringing these issue to our attention.
