### ISSUE TITLE
Issue with tickMarkFormatter and timezone

### ISSUE THREAD

**Issue by x1i4b1x2** [tradingview/lightweight-charts#1316]
**Lightweight Charts™ Version:** latest

I'm implementing timezone support with timeFormatter and tickMarkFormatter, but the tickMarkFormatter at tickMarkType 2 (DayOfMonth) still starts the day as UTC.

<img width="376" alt="Screenshot 2023-03-29 at 2 48 31 PM" src="https://user-images.githubusercontent.com/100806945/228540082-10d37b03-8562-4ad3-a502-7dfa1197480c.png">

<img width="382" alt="Screenshot 2023-03-29 at 2 48 47 PM" src="https://user-images.githubusercontent.com/100806945/228540150-63d758d9-36b2-4929-abe2-315d69b3984e.png">

Thoughts?

**Comment by SlicedSilver** [comment]
The `tickMarkFormatter` is called with three arguments: https://tradingview.github.io/lightweight-charts/docs/api#tickmarkformatter

The second argument is [TickMarkType](https://tradingview.github.io/lightweight-charts/docs/api/enums/TickMarkType) which lets you know the type of tick mark. You can check if that is equal to `TickMarkType.DayOfMonth`, and then rather return the day only instead of the full date string.

If the formatter function returns `null` then the default tick mark formatter will be used as a fallback. So you can use the fallback for all cases except `Time` and `TimeWithSeconds`. This is most likely what you would like to do if you only want to change the time displayed.

**Note that the returned string should be the shortest possible value and should have no more than 8 characters**. Otherwise, the tick marks will overlap each other.

The other alternative is to change the date values for the data before giving them to the library as mentioned here: https://tradingview.github.io/lightweight-charts/docs/time-zones#how-to-add-time-zone-support-to-your-chart

**Comment by x1i4b1x2** [comment]
This is how I'm approaching the tickMarkFormatter.

<img width="583" alt="Screenshot 2023-03-29 at 5 00 59 PM" src="https://user-images.githubusercontent.com/100806945/228581359-9fea2e38-ae69-42ec-8e21-effadf2af695.png">

The only problem is the mismatch with the timeFormatter.

When the tickMarkFormatter with TickMarkType.DayOfMonth fires, it isn't midnight in the timeFormatter with the timezone, the tickMarkFormatter still starts the day as UTC.

Where the tickMarkFormatter starts the day...
<img width="325" alt="Screenshot 2023-03-29 at 5 04 45 PM" src="https://user-images.githubusercontent.com/100806945/228582574-bad94b15-b49d-4380-9e81-997970b815ac.png">

The timeFormatter correctly points out that it is not midnight in the timezone, but it is midnight in UTC (I'm in GMT+2).
<img width="352" alt="Screenshot 2023-03-29 at 5 05 33 PM" src="https://user-images.githubusercontent.com/100806945/228582865-2cbbd7e7-664d-4515-9fdf-4f7197b0bc9d.png">

The timeFormatter code is like to tickMarkFormatter without the TickMarkType.

**Comment by SlicedSilver** [comment]
Right, so the issue is that the crosshair label doesn't display the same time as the tick mark.
It's not possible to control the placement of the tick marks, so in this case the simpler solution is to correct the timestamps in the data before it supplied to the library. https://tradingview.github.io/lightweight-charts/docs/time-zones#how-to-add-time-zone-support-to-your-chart

Then you wouldn't need to adjust the tick mark and time formatters.

**Comment by x1i4b1x2** [comment]
Got it, so literally adding the offset in seconds to the timestamp? I guess this only applies to hourly or similar intervals, right? For timestamps where time is not necessary like daily/monthly that can change the date entirely.
