### ISSUE TITLE
Custom shapes for SeriesMarkers

### ISSUE THREAD

**Issue by OmerFI** [tradingview/lightweight-charts#1318]
![placeholder-image](https://user-images.githubusercontent.com/54645034/229026155-9ede077c-3127-40d2-92a7-b51033509b92.png)

**Is your feature request related to a problem? Please describe.**
I want to be able to set custom shapes for [SeriesMarkers](https://tradingview.github.io/lightweight-charts/docs/api#seriesmarkershape) other than "circle" | "square" | "arrowUp" | "arrowDown"

**Describe the solution you'd like**
maybe a SVG, or image URL can be provided

**Comment by romfrancois** [comment]
Out of curiosity, why not rely on [createShape](https://www.tradingview.com/charting-library-docs/latest/api/interfaces/Charting_Library.IChartWidgetApi#createshape) and add one of the shapes defined [here](https://www.tradingview.com/charting-library-docs/latest/customization/overrides/Shapes-and-Overrides)

**Comment by OmerFI** [comment]
I want to add the following png shapes:
![buy_low_arrow](https://user-images.githubusercontent.com/54645034/229550782-2425b575-6732-4e08-9c7c-552df981691c.png)
![buy_moderate_arrow](https://user-images.githubusercontent.com/54645034/229550790-98542efd-2242-4f67-934f-6d7240bfd3ef.png)
Is it possible with that

**Comment by romfrancois** [comment]
Apologies there was a mixup with my tab and my comment went to the wrong thread :(

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
