### ISSUE TITLE
appending to the beginning of the array using update() method

### ISSUE THREAD

**Issue by OtabekEshpulatov** [tradingview/lightweight-charts#1340]
can i add a new object to the beginning of the candlestick bars array. Using update() method to add  a new bar only adds when a new element is newer than the last added element, Is there any trick to add older data anyway?

**Comment by SlicedSilver** [comment]
It is only possible to update the last value for the series (or add a new value). If you need to change (or add) any of the other data points then you need to use the `setData()` method on the series ([documentation](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#setdata)).

If you are only looking to add new data to the beginning of the series then you could instead add a new series with only the new points and ensure that all the options are the same. It will then appear as if it is a single series. The obvious difference would be how you will need to interact with the APIs since it will be more than one series. So this is only a viable option in a few specific cases.

**Comment by SlicedSilver** [comment]
Related: https://github.com/tradingview/lightweight-charts/discussions/1341
