### ISSUE TITLE
Countdown to bar close

### ISSUE THREAD

**Issue by tpunt** [tradingview/lightweight-charts#1345]
Having a countdown to bar close, similar to what TradingView has just under the price line, would be good.

Creating this issue to gauge interest from others/core devs.

**Comment by roysupriyo10** [comment]
fully support this

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples (see above links):
- Rectangle Drawing Tool (shows how to add labels using a plugin)

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.

**Comment by tpunt** [comment]
Hey @SlicedSilver. Thanks for the response. This ia a bit belated, but I have finally gotten around to implementing this as a plugin. It is still a rather preliminary implementation, but it can be found in [lwc-plugin-countdown-to-close](https://github.com/tpunt/lwc-plugin-countdown-to-close).

I had some trouble with this, however. There are things that LWC has not exposed to plugin developers that made this rather awkward to do. The two main problems I encountered were:
 1) No access to `ISeries::lastValueData()`. Since this is apart of the series interface, plugins that deal with series data really need access to this. As a hack, I had to provide an option for the plugin to define its own way of accessing the last data series value (`fetchLastDataPoint`) to allow for `LineSeries` to return `value`, `CandlestickSeries` to return `close`, etc. This also has the knock-on effect of not having access to `LastValueDataResultWithData.color`, and so when candlestick data causes the built-in last price line to change colour, including its corresponding price axis label, the countdown timer cannot change colour in the same way.
 2) No access to converting `LineStyle` when drawing it. This is done in `setLineStyle()` internally, and so any line drawings in plugins will need to copy this function in order to be consistent with the rest of the library.

Unless I am missing something here, I would like to propose exposing the `SeriesApi<TSeriesType>::_series` property via a `series()` method (similar to `seriesType()`), as well as exposing `setLineStyle()` from `lightweight-charts/src/renderers/draw-line.ts`. I am happy to create a pull request if you agree with this. I'll then circle back to this plugin to make the improvements and publish it on NPM for others to use.

This is a quick demo in the current form:
`LineSeries`:

https://github.com/user-attachments/assets/5ae4910d-6149-444d-accb-99e38f37f1b9

`CandlestickSeries`:

https://github.com/user-attachments/assets/f8833d8e-31ed-46f9-a45f-75dd2c6c4ff8

Thanks!

**Comment by SlicedSilver** [comment]
I'm a bit reluctant to directly expose some of the internal data structures as part of the API since once it becomes part of the public API then it becomes something which is harder to change in the future without a breaking change. Internally the property names of that object would be minified anyway so exposing all of `LastValueDataResult` would also increase the bundle size.

I do see the need for a simple way to get this data because it isn't as simple as reading `value` or `close` because custom series might use different names for these. So perhaps you could add `ISeriesApi.lastValuePrice()` which gives you the price value used for the price scale (aka 'close' / 'value' / something custom), and `ISeriesApi.lastValueColor()` which gives you the color value.

Or perhaps `ISeriesApi.lastValueData()` but only include `noData`, `price` and `color` in the object for now. We can add more if requested in the future but would prefer if we keep it as small as possible for now.

Could you explain the benefit of exposing `setLineStyle` in more detail? It seems a rather simple function, and I'm not sure why the plugin would need to have access to the actual implementation.

**Comment by tpunt** [comment]
That's a good point. I quite like your suggestion regarding a single, unified method of `ISeriesApi.lastValueData()`. I'm happy to create a PR with that to help resolve this issue.

Regarding `setLineStyle`, it's more for when plugins will be drawing lines where plugin developers would like to use the same `LineStyle`s as the core library already defines. We can just copy the function directly from LWC (which is what I have done [here](https://github.com/tpunt/lwc-plugin-countdown-to-close/blob/4ea2b2dd699640ddacfd15f75c78e4be57b59fd9/src/pane-renderer.ts#L51)), but this just feels wrong to do. For example, if LWC adds more line styles in future, then these new styles will not work for any plugins that have copied the code until they update their code. So this means plugins should either define their own line styles that are independent from those used by the core of LWC (which means inconsistencies and dealing with two types of line styles), or LWC should expose the same line style drawings that its features currently depend on.

**Comment by SlicedSilver** [comment]
If you are up to it then it would be appreciated if you open a PR. Some helpful advice, make sure to test your changes with a production build of library. Our build process aggressively mangles property names for any types that it determines aren't publicly exposed so that the bundle size can be smaller. This means it is important that the public interface and the internal interface aren't the same and that at the API level there is a 'conversion' (which typically means constructing the result with an explicitly new object with each property specified). If you get stuck then ask for help because it can be confusing if you don't know how it works.

For the `setLineStyle`, I suppose that we could expose a few helper functions via an additional (optional) parameter on the `draw` and `drawBackground` methods for `IPrimitivePaneRenderer`.
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IPrimitivePaneRenderer#draw

For example:
```
interface DrawingUtils {
    setLineStyle(ctx: CanvasRenderingContext2D, style: LineStyle): void;
}

export interface IPrimitivePaneRenderer {
	draw(target: CanvasRenderingTarget2D, utils?: DrawingUtils): void;
	drawBackground?(target: CanvasRenderingTarget2D, utils?: DrawingUtils): void;
}
```

**Comment by tpunt** [comment]
Thanks for the pointers, @SlicedSilver.

I'm not sure I fully understood the problems a production build may encounter. However, I followed your advice of constructing new objects, as well as making a prod build that uses my countdown plugin with the new API changes (https://github.com/tpunt/lwc-plugin-countdown-to-close/compare/with-new-api-changes).

I have created a PR (https://github.com/tradingview/lightweight-charts/pull/1956) now for these changes.
