### ISSUE TITLE
Add Padding to timeScale

### ISSUE THREAD

**Issue by sulhadin** [tradingview/lightweight-charts#1363]
I'm currently facing a difficulty with timeScale in the Lightweight Chart library. As of now, it seems there is no way to add padding to the timeScale. In my use case, it would be extremely beneficial to have some padding for better chart visualization and user experience.

![Screenshot 2023-05-18 at 03 41 16](https://github.com/tradingview/lightweight-charts/assets/1446064/f326e72c-20c6-4a2d-a9a1-df175087d450)

**Comment by SlicedSilver** [comment]
Could you please highlight on the image where you would like to add padding?
- Is it the top and bottom of the series? (can be done using scale margins, explained in this example: https://tradingview.github.io/lightweight-charts/tutorials/how_to/price-and-volume)
- Left and right of the chart? (can be done using css on the container div)
- Or is it the tick marks within the timescale?

**Comment by sulhadin** [comment]
Hi @SlicedSilver, thank you the quick response.

- it is the tick marks within the timescale. 

In my current project, I have the necessity to enhance the height of the timescale for better visibility and readability. Furthermore, adding padding to the right and left sides of the timescale would greatly improve the aesthetic appeal of the chart.

In my specific case, the container div's padding is set to zero due to the design requirements. Regrettably, this configuration results in the tick marks extending to the edges, causing a somewhat cluttered appearance that detracts from the overall presentation.

Thus, having the ability to customize the height and padding of the timescale would be a highly valuable feature, enhancing the adaptability of the library for various design needs and ultimately improving the user experience.

![Screenshot 2023-05-18 at 03 41 16](https://github.com/tradingview/lightweight-charts/assets/1446064/15abefaf-fd67-4513-817a-add25e74efe9)

**Comment by SlicedSilver** [comment]
👍 In summary,
- Option for vertical padding within the timescale (above and below the tick mark text).
    - This would adjust the height of the timescale automatically. 
- Improve rendering of the time scale tick marks so that they don't get cut-off at the edges.

Improving the rendering of the tick marks to prevent the labels getting cut-off would require some extra consideration on our side on how best to achieve this. In the static image case it is rather simple fix but since the chart is dynamic, and can be scrolled, extra attention is required to handle the transitions in and out for the labels while interacting with the chart.

**Comment by sulhadin** [comment]
Hello again @SlicedSilver 

I wanted to report another  issue regarding with the time scale labels.

In the screen shot I am sharing below, some gap between two labels are larger than the others. Some texts are bolder while the others are thinner.

 Is there any solution to those issues?


![Screenshot 2023-08-02 at 12 30 15](https://github.com/tradingview/lightweight-charts/assets/1446064/da614674-18d8-40ba-bede-339f2ba5756b)

**Comment by nichita-pasecinic** [comment]
Hi @SlicedSilver, 

It is possible to add a padding right for the series itself, so it would start with an offset. I see the property `rightOffset` on `timescale` which is calculated in bars and not convenient for my case. In my case the timescale range is not uniform and I can't calculate or set a specific visible range, I just show the data on the chart. 

It is possible to add some sort of padding/margin for that purpose ?

Is this related to this issue ?


![image](https://github.com/tradingview/lightweight-charts/assets/98735377/e93469d1-de99-46b0-ad95-7195a74b8e97)

The screenshot is from Binance and I believe they're using the `rightOffset` because the data is normalized and they can

**Comment by SlicedSilver** [comment]
The chart shown in the Finance screenshot is actually a different library created by TradingView called 'Advanced Charts' [More Info](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts)

To answer your question, you could use the [`barSpacing`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#barspacing) to know the width that each bar takes up in pixels and then calculate the right offset that you would like to use. i.e. you can use barSapcing to convert between pixels and barCount for the horizontal axis.

This can also be calculated if the zoom have changed by using the width of the timeScale, and the visibleLogicalRange. See the [`ITimeScaleApi`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi) interface for more details.

**Comment by SlicedSilver** [comment]
There is now an minimumHeight option for the timescale which can be set via its options. 

https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#minimumheight

**Comment by iphyman** [comment]
@SlicedSilver Is it possible to show limited number of timescale marks and with constant time increments
![time](https://github.com/tradingview/lightweight-charts/assets/86075509/3451ffc9-27ee-468d-a319-1a2288227762)

For example in the above screen shot we can see the times clustered and not uniform, I want to show minimum number of marks with a constant increment of a minute or so

**Comment by SlicedSilver** [comment]
One of the other additions to the library in v4.1 is the ability to customise the tick marks behaviour on the time scale. The test case show how to use this new API: https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/horizontal-price-scale.js
If you look at the `fillWeightsForPoints` function, and returned the same weight for every point then you should get closer to your desired behaviour.

Additionally, if you used an additional series on the chart which contained only whitespace data (data with time values but no price values) which had a consistent number of data points then you can make the time scale linear. Since the library will plot a point for every data point provided, if your whitespace series had a data point every minute then the result would be a linear time scale.

**Comment by iphyman** [comment]
Thank you very much, will experiment with whitespace data

**Comment by sulhadin** [comment]
@SlicedSilver Hi,

Thank you for bringing the new minimumHeight feature. When I use it the new appearance need padding too. How can I center the time scale labels?

Additionally, when I use this configuration;

```
    timeScale: {
      fixLeftEdge: true,
      fixRightEdge: true,
    },
```

the timescale labels overlaps as you can notice from the screenshot below.

![image](https://github.com/tradingview/lightweight-charts/assets/1446064/7f47b74c-ac99-4d80-af6c-80cffde7bbe7)

**Comment by SlicedSilver** [comment]
The `minimumHeight` option is intended for use when you need to increase the timescale for drawing larger items with Plugins. There aren't any options to adjust the internal padding of the timescale at this time.

Regarding the overlapping of the timescale tick labels. I would recommend using the [`tickMarkMaxCharacterLength`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#tickmarkmaxcharacterlength) option to set a larger label length.
