### ISSUE TITLE
Error: Invalid Relative Dependency Path when Installing lightweight-charts via pnpm

### ISSUE THREAD

**Issue by kouraf** [tradingview/lightweight-charts#1364]
**Lightweight Charts™ Version:** 

**Steps to reproduce:**

- Create a new project or navigate to an existing project.
- Open the terminal and execute the following command: `pnpm add lightweight-charts`
- Observe the error message received.

**Actual behavior:**

i got this error 
```
ERROR: /@alloc/quick-lru@5.2.0 is an invalid relative dependency path
```

**Expected behavior:**

The lightweight-charts package should be successfully installed, allowing me to utilize its features within my project.

**Screenshots:**

![image](https://github.com/tradingview/lightweight-charts/assets/22027736/40a24c79-39c1-44d6-a596-e7ee8bd295dd)

**Environment:**

- Operating System: Arch Linux
- Node.js version: 18.12.1
- pnpm version: 7.18.2

**Comment by SlicedSilver** [comment]
I'm unable to reproduce this issue on my side. Using `pnpm add lightweight-charts` in a new project worked as expected.

It looks like an issue with `pnpm` and is unrelated to the library since we don't have `@alloc/quick-lru@5.2.0` as an import or dependency. 

Could you try using a newer version pnpm

**Comment by Veer0x1** [comment]
update your pnpm version using command ```pnpm upgrade```
