### ISSUE TITLE
implement bionic candles

### ISSUE THREAD

**Issue by sanikolov** [tradingview/lightweight-charts#1378]
**Is your feature request related to a problem? Please describe.**

Yes. As far as I could tell you can't implement a study or indicator that can render bionic candles in tradingview charts.
The reason is that bionic candles do not have wicks - the entire low to high range is the candle.
For this reason it is not enough to chop off the wicks to construct a bionic candle.
The inventor of bionic candles describes what they are here https://www.youtube.com/watch?v=eWS4rBEUn2w .
In a nutshell, a bullish bionic candle is colored gray from low to close and red from high to close.
Similarly, a bearish bionic candle is gray from high to close and green from low to close.

**Describe the solution you'd like**

Implement them as an addition to this list: bars, candles, hollow candles, columns, line, line with markers, etc...
Make it possible to customize the colors.
While gray, red, green may be good defaults, people have also used other colors.
So called `key candles` may be colored differently, to stand out, but this can be implemented in a separate indicator.

**Additional context**

The inventor of bionic candles gives solid arguments in his [youtube series](https://www.youtube.com/@BionicsForexAlgorithms/videos) and [forexfactory thread](https://www.forexfactory.com/thread/1113712-bionic-chart-the-easiest-forex-navigation) why these candles
are superior to other kinds of candles for analysis of super liquid instruments like EURUSD.
The depth and breadth of research on all things trading (pips per minute, candles, futures DOM as an aid to spot forex trading, etc) he has done is stunning. This guy is no ordinary trader.
Let's show some humility and admit that innovation like what he has done is still possible in this modern day and age.
MT4 indicators for bionic candles are available in the forexfactory thread above (page 1) for free download, if a reference implementation is desired.
Full disclosure - I do not know this guy, never communicated with him, have no affiliation.

**Comment by SlicedSilver** [comment]
It would be possible to render a chart like that currently on Lightweight Charts by tweaking the data slightly and using two separate candlestick series attached to the same price scale. Essentially, you could have one series plotting the bottom half of the bars (with the values adjusted so no wicks are drawn, or adjusting the styling options), and another series handling the top half.

Additionally we are working on a system for custom series types to be added to the library. This specific series type would be easy to implement and we might add it as an example when we release the new feature. So there should be a better solution available soon.

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples (see above links):
- Whisker Box Series

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
