### ISSUE TITLE
Histogram has some space below bars when markers are added

### ISSUE THREAD

**Issue by plagun98** [tradingview/lightweight-charts#1382]
**Lightweight Charts™ Version:** 4.0.1

**Steps/code to reproduce:**

Add histogram to the chart, set priceScaleId: '', add markers to the histogram series

**Actual behavior:**

Some space appears below the histogram

**Expected behavior:**

No space between histogram and bottom of the chart

**Screenshots:**

<img width="531" alt="image" src="https://github.com/tradingview/lightweight-charts/assets/17813714/b0993d66-0046-4872-89a5-1c92b3a58b89">

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/exuqzLh5/

**Comment by SlicedSilver** [comment]
Thanks @plagun98.
Having a look at your provided code sample I can't see anything that you've done incorrectly, and I can see the same behaviour as you show in the screenshot.

We would need to investigate further but I would assume that we are leaving space under the series because there might be a marker that we could want to drawn in that space. So the library might need a `ignoreMarkersDuringAutoScaling` option added to the PriceScaleOptions.

I'll mark this as a `bug` for now.

**Comment by winfirm** [comment]
I met the same case,  when I applied MACD histogram to  candle chart  in  a  single chart object,  there came some gaps in  both histogram and candle area.
