### ISSUE TITLE
Add priceFormatter in PriceScaleOptions

### ISSUE THREAD

**Issue by Daxdop** [tradingview/lightweight-charts#1391]
I would like to have on the same chart a dollar-valued series and a percentage-valued series, but being the priceFormatter chart-specific rater than scale-specific it seems to me that there is not this possibility.

A priceFormatter prop in the PriceScaleOptions would enable this double scale chart.

Note: PriceScaleMode does not solve the problem as I don't want the percentage change from the first visible data value, but the value itself is a percentage.

Image:
<img width="540" alt="Schermata 2023-07-03 alle 23 21 09" src="https://github.com/tradingview/lightweight-charts/assets/104645665/12298f4e-79b9-4860-b428-b0cfc6867deb">

**Comment by SlicedSilver** [comment]
Each series can specify its own [unique price formatter function](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat). This allows you format the price value as a percentage for the one series, and as a dollar amount for the second series.

So the solution is to specify the formatter within the series options instead of the price scale options.

I've created an example here: https://codesandbox.io/p/sandbox/lightweight-charts-multiple-price-formatters-h2lcv3

This is essentially the code required:
```js
const lineSeries = chart.addLineSeries({
    priceFormat: {
      type: "custom",
      formatter: function (price) {
        return `$${price.toFixed(2)}`;
      },
    },
  })

const candlestickSeries = chart.addCandlestickSeries({
  priceScaleId: "left",
  priceFormat: {
    type: "custom",
    formatter: function (price) {
      return `${price.toFixed(2)}%`;
    },
  },
});
```

- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#priceformat
- https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatCustom
- https://tradingview.github.io/lightweight-charts/docs/api#priceformatterfn

**Comment by Daxdop** [comment]
Thank you very much!
