### ISSUE TITLE
Facing Chart Update Issue in lower timeframe using UTC Timestamp

### ISSUE THREAD

**Issue by toxicdeep** [tradingview/lightweight-charts#1401]
**Lightweight Charts™ Version: 4.0.1**

Have created a chart in a lower intraday 5 Min timeframe-based data by converting `YYYY-MM-DD HH:MM` to epoch/time
`isUTCTimestamp: true, // Set to true to use epoch timestamps`

### am trying to update the chart [`chart.update()` ] with live feed but getting an **ERROR**

`ncaught TypeError: Cannot read properties of undefined (reading 'year')`
`at ps (lightweight-charts.standalone.production.js:6877:37)`
`at ks.Om (lightweight-charts.standalone.production.js:6997:30)`
`at Zs.Hm (lightweight-charts.standalone.production.js:7690:26)`
`at Us.update (lightweight-charts.standalone.production.js:7429:32)`

I have tried both ways to use the time in epoch as well as the `YYYY-MM-DD HH:MM` format, but unable to get the updated chart output.
It will be a great help if anyone resolves this for me.
thanks in advance

**Comment by SlicedSilver** [comment]
You may get a few more useful debugging messages in the console if you use the development build instead of the production build
`lightweight-charts.standalone.production.js` → `lightweight-charts.standalone.development.js`

If you want to use intraday resolutions (such as minute data) then you need to use a timestamp value for the [`time`](https://tradingview.github.io/lightweight-charts/docs/api#time). It should be a number like this: `1529899200` which is a [`UTCTimestamp`](https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp). Have a look at the linked documentation for a more detailed explanation and code sample.
