### ISSUE TITLE
TimeScale is not regular when data has gaps

### ISSUE THREAD

**Issue by Danita** [tradingview/lightweight-charts#1426]
I'm using LightweightCharts to debug flight simulation data, because it's the fastest I've found and it looks great! That said, I have a problem that I can't seem to figure out how to solve, so I figured must be a missing feature. 

I get periodical updates from the server so I draw a timeline with an area chart. I can connect and disconnect from the data source at any time; and I don't care if the data is drawn or not at the gaps, but I need the graph to keep the time scale consistent, that is, always N pixels = N amount of time. See chart below: it was drawing realtime until 21:49:57, then I disconnected from the data source and resumed at 21:52, but the chart shows it next to the previous data.

![imagen](https://github.com/tradingview/lightweight-charts/assets/754783/0065ed69-b76e-464e-8184-81d08492f640)

A possible solution would be to include a timeScale option to enable the scale to be consistent. Maybe another option to specify if the data must fill the gap (a straight line from the last point before the gap to the new one after it) or to keep the gap without data.

**Comment by SlicedSilver** [comment]
In our charting library, the time scale operates in a specific manner to visually represent data points over time. For each unique time value or data point, a corresponding position is allocated on the time scale. These points are evenly spaced with the same width, which we refer to as "bar spacing." The key aspect to note is that the library does not introduce any additional gaps or spaces between the points on the time scale.

The reason behind this approach lies in the fact that the library lacks information about the expected resolution or desired gap between the bars in time. For instance, if you prefer a specific interval such as 5 minutes between each bar on the time scale, the library does not possess that knowledge by default. Instead, it simply displays the data as it is provided to it.

This means that if there are missing data points within the specified time range, the library will not automatically create gaps or adjust the positioning of the existing points. It will visualize the available data points as they are, without assuming any particular spacing between them. Therefore, if there are time intervals without corresponding data, those intervals may appear as visually contiguous bars on the time scale.

It's important to keep in mind that the library's behavior in handling missing data is primarily driven by the data provided and does not account for predetermined spacing or assumptions regarding the temporal resolution.

### possible workaround / solution

You could create a separate series on the chart which contains only whitespace data (so that it doesn't render anything). Whitespace data is just a data point which only has a `time` value and no `value`. These essentially act as 'gaps'. 
If you create the whitespace series such that there is a whitespace data point at each possible time you would like on the time scale then the time scale will be correctly spaced out.

When the actual line series is added to the chart then it will match it's times with that on the time scale and thus be positioned correctly, and if there are missing values then the space will be visible and the line will be correctly drawn between the actual data points.

So to create the whitespace series, you would need to consider what time interval you are expecting (for example, one bar per second) and then create a series which has a whitespace data point every second.

It is important that the time values exactly match between the data point on the line series and the whitespace series, so you should probably round your timestamps to the nearest second in this case.

**Comment by Danita** [comment]
Oh, that workaround could definitely work! I still find it a bit odd the "scale is not a scale" philosophy with this particular library, but I understand where you're coming from since it's intended to deal with very particular data. Thank you for your detailed response and for making this library open source!

**Comment by SlicedSilver** [comment]
> I still find it a bit odd the "scale is not a scale" philosophy with this particular library

I agree that at first it appears odd, but it is mainly because the library is designed to be used with financial data and this is actually the preferred way to do this (close gaps of inactivity, and also don't display gaps between trading sessions which are usually something like 9am-4pm, and you wouldn't want to have the majority of the chart appearing empty).

**Comment by Danita** [comment]
Precisely. Thanks.

**Comment by Shannanigans** [comment]
I would expect that time proportionality when dealing with sparse data without resorting to representing empty bins is optionally supported.

Typically this is easily achieved in other charting libraries by specifying the y axis data type as numeric and passing the time values as unix timestamps. Using callbacks to format the timestamps to user readable values where necessary (tooltips, ticks ect). In this manner the y-axis scale is consistent and samples are represented proportionally relative to each other.

Opting out is trivially achieved by specifying the y axis data type as non numeric (string ect), passing date string data which the chart can then display uniformly regardless of differences between y-axis values.

Why not support both options? It is true that trading view is opinionated as a financial tool, however the light weight tools are generalised and likely to be used in a large range of applications, not all of which will want to collapse time gaps (due to user expectations) or be forced to represent empty bins.

Some applications cannot guarantee data density across all charts and do not want to represents many empty bins in response data and enforce unnecessary constraints on data queries to meet the requirements of a charting library, especially when the issue could be solve in the charting library itself relatively trivially.

**Comment by garmoshka-mo** [comment]
you will need to justify data with such function:

    export function justifyData(data, span = 10) {
      var justifiedData = [], lastTime
      data.each(item => {
        var {time} = item
        while (lastTime && lastTime + span * 1.4 < time) {
          lastTime += span
          justifiedData.push({time: lastTime})
        }
        justifiedData.push(item)
        lastTime = time
      })
      return justifiedData
    }

    yourSeries.setData(justifyData(data))
