### ISSUE TITLE
param.hoveredSeries in subscribeCrosshairMove only contains data for the latest point

### ISSUE THREAD

**Issue by hosokawashinnosuke-vt** [tradingview/lightweight-charts#1433]
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:4.0.1**

**Description**
I am encountering an issue where `param.hoveredSeries` in the `subscribeCrosshairMove` event only contains data when hovering over the latest point in a series. I expected it to contain data for any point that is being hovered over, not just the latest one.

**Steps to Reproduce**
1. Create a chart with multiple data points using Lightweight Charts.
2. Implement `subscribeCrosshairMove` event listener.
3. Log `param.hoveredSeries` when moving the crosshair over the series.
4. Notice that `param.hoveredSeries` only contains data when the latest point in the series is hovered.

**Expected Behavior**
`param.hoveredSeries` should contain data for any point that is being hovered over in the series, not just the latest one.

**Actual Behavior**
`param.hoveredSeries` only contains data when hovering over the latest point in the series.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Environment:**
- Lightweight Charts version: [e.g., 3.3.0]
- OS: [e.g., Windows 10]
- Browser: [e.g., Chrome 96]

**Code Sample**
Provide a minimal code sample that reproduces the issue.
```javascript
// your code here
chart.subscribeCrosshairMove(function (param) {
          console.log(param.seriesPrices)
          param.seriesData.forEach((data, series) => {
              console.log('Data: ', data, 'Series: ', series);
          })
})

**Comment by NekitCorp** [comment]
Hello, @SlicedSilver 

I see that this issue is closed, but I’m not sure if the behavior described in the issue is the expected one when hovering over a series. Could you please help clarify?  

In my example, I subscribe to `subscribeCrosshairMove` and log `hoveredSeries` when it exists. As you can see, it only logs when hovering over the last point in the series, while hovering over any other points does not trigger any messages.  

Is this the expected behavior? And is there any other way to detect when hovering over any part of the series?  

Thank you!

**Example:** https://jsfiddle.net/uqkv4108/7/
**Lightweight Charts™ Version:** 5.0.3
