### ISSUE TITLE
Histogram bug when at specific zoom level

### ISSUE THREAD

**Issue by x1i4b1x2** [tradingview/lightweight-charts#1435]
**Lightweight Charts™ Version:** 4.0.0

When zooming at a specific level you can see that the histogram gets more transparent and it has a weird look.

https://github.com/tradingview/lightweight-charts/assets/100806945/15746c57-95e8-456d-a003-72ee7e864add

**Comment by SlicedSilver** [comment]
That is the expected behaviour of the histogram series (at least when I check on the latest release).

The renderer has a few goals:
- Ensure that each rectangle / line is perfectly aligned to an actual pixel on your screen.
- try to keep a visible gap between bars (unless there isn't enough space to do so, like at very small sizes).
- try to keep all the bars a consistent width (all bars should be the same width)

Because of these constraints (and potentially a few others I've forgotten), the rendering of the histogram will have this visual effect at certain zoom levels. The alternatives have other downsides like blurry shapes, or difficultly distinguishing between adjacent bars.

If you are interested, the algorithm is explained further here: https://tradingview.github.io/lightweight-charts/docs/plugins/pixel-perfect-rendering/widths/columns

**Comment by ingria** [comment]
Thanks for the explanation.

Histogram still looks strange in some cases, for example when gap size is inconsistent across the graph:

![lightw](https://github.com/tradingview/lightweight-charts/assets/2178368/cde5d281-4fd1-4704-a47a-e6faf7d3774d)

This is how the same graph is rendered in another charting library:

![chartjs](https://github.com/tradingview/lightweight-charts/assets/2178368/67c36c5b-9160-44b9-bd3d-e1bb5c505006)

**Comment by SlicedSilver** [comment]
Another goal is that it should match the appearance that we have on tradingview.com and for that reason we are unlikely to change this.

However, if you would like to implement a different rendering behaviour then it would be possible to create your own version of the Histogram series using a Custom Series plugin. https://tradingview.github.io/lightweight-charts/docs/plugins/custom_series

The [stacked bars plugin example](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/stacked-bars-series) could be used as a starting point, and you could remove the 'stacking' part of the code. You could then replace this calculation here: https://github.com/tradingview/lightweight-charts/blob/b7101dc2ac4891c561197a8470baad1a3154442d/plugin-examples/src/plugins/stacked-bars-series/renderer.ts#L78-L84

**Comment by ingria** [comment]
Thanks for the tip, will look into that!
