### ISSUE TITLE
Bold timescale values are not always correct and there is no option to turn this functionality off

### ISSUE THREAD

**Issue by humpedli** [tradingview/lightweight-charts#1438]
**Lightweight Charts™ Version:** 4.1.0

Automatic bold texts are sometimes not working very well on timescale (x axis). If this feature could be disabled, it would be nice.

Good example (month-day):

<img width="1252" alt="month" src="https://github.com/tradingview/lightweight-charts/assets/8111798/37594a6b-0ea0-4188-9f97-d9e2411b90e7">

Bugs (year-month):

<img width="1256" alt="year" src="https://github.com/tradingview/lightweight-charts/assets/8111798/9333145b-8f05-4d73-a937-f4fe7f17ed06">
<img width="1264" alt="three_years" src="https://github.com/tradingview/lightweight-charts/assets/8111798/12a0fdf6-7358-48ea-81aa-6f1758a4d108">

We are in GMT+2 timezone, so I am converting datetimes to UTC to pass to the chart, later I use timeFormatter to display them in correct time zone. If I'm not doing this I also have issues with bold texts (HH:mm - 00:00 - not bolded vs 02:00 - bolded). In bugs section on second screenshot you can see that first 2 bold texts are correct, the last one is not. Data is the same for all 3 texts: HH:mm = 00:00.

The best would be an option to turn this functionality off, because it's not always needed.

I saw that you closed this request, but it would be a good feature to disable bold texts to ignore unwanted bugs: https://github.com/tradingview/lightweight-charts/issues/545

**Comment by SlicedSilver** [comment]
Lets break this into 2 separate topics:
1. Ability to disable bold text on the timescale.
2. Bug: Incorrect tick mark has been made bold.

---

### 1. Option to disable bold text for tick marks in the timescale 

This seems like a reasonable request.

---

### 2. Incorrect tick mark has been made bold

It would seem that the correct tick mark is being made bold, but the formatted text is incorrect.

Could you please share the data you've used for this example? Or even better, a small reproducible example on a site like jsFiddle / code sandbox?

My initial thought is that the code you are using to handle the GMT+2 timezone difference (the formatter) might have a slight bug in it. Perhaps you are subtracting by a fixed amount of milliseconds instead of using the browser APIs for this. Something as strange as the few leap milliseconds that are added/remove at the end of each year might be causing this problem.

**Comment by humpedli** [comment]
@SlicedSilver thank you for your answer.

You were right, I used date-fns to parse and modify the timestamp and this solution was buggy. I discovered this bug while I was creating JSFiddle to visualize my chart.

Anyway, here is the JSFiddle for others (if anyone experience the same issue): https://jsfiddle.net/egym7w6r/
If you uncomment the marked 2 lines, then you can see the bug.

Now I replaced the parser with native browser API, thanks for pointing out the problem.

For option 1: I think it will be still helpful if we can disable bold text on timescale. So from now, it is a feature request instead of a bug report.

**Comment by SlicedSilver** [comment]
Great. I'll leave the issue open for the bold option feature request.

With regards to the browser APIs, it is often easy to use the [setHours](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours) method to modify a date to be exactly at midnight (in the current timezone).
```js
const d = new Date();
d.setHours(0, 0, 0);
```

It works with negative numbers as well, so something like this can go 2 hours backwards:
```js
const d = new Date();
d.setHours(d.getHours() - 2);
// or
d.setMinutes(d.getMinutes() - 120);
```

**Comment by SlicedSilver** [comment]
@ingria Could you describe which font settings you would like to customise? Is it just the weight of the font used for bold text?

**Comment by Jokero** [comment]
+1 for the option to disable bold font. I was wondered why this "feature" even exists as it just distracts attention

**Comment by ingria** [comment]
@SlicedSilver in my case customizing just the weight would be enough, but customizable color and size would also be useful.
