### ISSUE TITLE
priceLineSource option seems not working

### ISSUE THREAD

**Issue by liesauer** [tradingview/lightweight-charts#1448]
**Lightweight Charts™ Version:** 4.1.0

**Steps/code to reproduce:**

```js
chart.addCandlestickSeries({
    priceLineSource: PriceLineSource.LastBar,
    upColor: '#26a69a',
    downColor: '#ef5350',
    borderVisible: false,
    wickUpColor: '#26a69a',
    wickDownColor: '#ef5350',
});
```

**Actual behavior:**

always show the last bar's price, not the last visible one.

**Expected behavior:**

always show the last bar's price, not the last visible one.

**Screenshots:**

![GIF 2023-10-21 17-10-20](https://github.com/tradingview/lightweight-charts/assets/8676741/c9a6eaa7-09d0-4a15-a445-1bbcb2de1302)

**CodeSandbox/JSFiddle/etc link:**

https://tradingview.github.io/lightweight-charts/docs/series-types#candlestick

and adding the `priceLineSource` option

**Comment by liesauer** [comment]
> If you want the price line source to be the last visible bar then you should use [`LastVisible`](https://tradingview.github.io/lightweight-charts/docs/api/enums/PriceLineSource#lastvisible), not `LastBar`.

i need the last bar, but it doesn't work.

**Comment by SlicedSilver** [comment]
There is probably some confusion about what the expected behaviour is so let me clarify this in more detail.

The [`priceLineSource`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#pricelinesource) sets which value is used for drawing the horizontal price line for that series. The two options are **LastVisible** (which will draw the line at the price value of the last visible price), and **LastBar** (which will draw at the latest price, even if it is scrolled out of view).
**This is working as expected. The line will be drawn at different places.**

Where the confusion is probably coming in is that the label on the price scale isn't attached to the price line, but is actually always meant to show the price of the last visible bar. This can be seen by reading the description in the [docs](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesOptionsCommon#lastvaluevisible):
> Visibility of the label with the **latest visible price** on the price scale. 

**So again, it is expected that the price label isn't affected by the `priceLineSource` option.**

---

There is a way to get your desired behaviour.
- You can set `lastValueVisible` to `false` so that the label is not visible
- Set `priceLineVisible` to `false` so that the price line isn't visible
- and then add your own price line at the value of the last bar
```js
const priceLine = mainSeries.createPriceLine({
  price: 460.0, /* latest price value */
  color: "red",
  lineWidth: 1,
  axisLabelVisible: true,
});

// and if you need to update the position you could do this:
priceLine.applyOptions({
  price: 480, /* new updated latest price value */
});
```

Here is an example showing the three different options: 
[codesandbox.io](https://codesandbox.io/p/sandbox/lightweight-charts-ts-starter-forked-jhygfw?file=%2F.codesandbox%2Ftasks.json%3A1%2C1)

**Comment by liesauer** [comment]
i see, so the `priceLineSource`only affects the line, the label always show the price of the last visible bar! it makes me so confused.

**Comment by liesauer** [comment]
btw, it there any usecases in real world? i really don't understand this out of sync behaviour.
