### ISSUE TITLE
The zoom does not work as expected

### ISSUE THREAD

**Issue by fullgream** [tradingview/lightweight-charts#1450]
**Lightweight Charts™ Version:** 

**Steps/code to reproduce:**

https://jsfiddle.net/honeyoff/s7px0rc5/48/

**Actual behavior:**

The zoom out doesn't work as expected.

**Expected behavior:**

Overall everything works great, I like the smoothness of the new points. The only problem is that I can't zoom out further than a few seconds. I realize this is due to the fact that there is a new dot every few milliseconds. If I change the time point counting behavior in the class, the zoom out works as expected. (const timeValue = this.to.time;)

I was trying to make a custom data series using a plugin system. The problem is that I never found a way to do the animation the normal way. There is no way to call the render function internally in custom series. Honestly in 3 days I am already out of ideas how else to do this task.

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/honeyoff/s7px0rc5/48/

**Comment by SlicedSilver** [comment]
Thank you for sharing the code sample. When I used your example I didn't notice any strange zooming behaviour. Could you perhaps create a short video showing the issue and explain what you are wanting to change in a bit more detail?

Perhaps you are talking about a 'minimum zoom level'? If so then by default the chart will only zoom out until there is a single data point per pixel. After that it will stop zooming out. The time scale options includes a setting for [`minBarSpacing`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/HorzScaleOptions#minbarspacing). If you set this to a small (but non-zero) number then you will be able to zoom out further (for example: `0.000001`).

> I was trying to make a custom data series using a plugin system. The problem is that I never found a way to do the animation the normal way. There is no way to call the render function internally in custom series. Honestly in 3 days I am already out of ideas how else to do this task.

It is possible to trigger the renderer from within a drawing primitive plugin. See the [attached](https://tradingview.github.io/lightweight-charts/docs/plugins/series-primitives#attached) hook which includes a method to request a rendering update.

A custom series shouldn't require such a method because the renderer will be called whenever the chart is adjusted, or a data point is added / changed.

**Comment by fullgream** [comment]
I've been experimenting with the schedule. I decided to add a new series of data to the chart, which will completely copy the first one, but without animation. It turned out to be an interesting behavior. On the time scale, the new chart moves with the same speed as the chart with animation, although there is no animation on the time scale. Another interesting behavior. If you switch from one tab to another for a minute, then coming back you can see that the data has collapsed into one heap. Most likely this happens because requestAnimationFrame stops working, but it certainly makes it harder to work with the task I chose :)

https://jsfiddle.net/honeyoff/s7px0rc5/59/
