### ISSUE TITLE
Tooltip with Multiple Series

### ISSUE THREAD

**Issue by ChristopherJohnson25** [tradingview/lightweight-charts#1451]
I have a tooltip with multiple series, it works almost as expected using iSeries API, but, I'd like to get the coordinate of the highest price/value so that the tooltip does not obstruct any data below it. Is this possible?

**Comment by SlicedSilver** [comment]
The y coordinate for a specific price value might be different for each series since they can be on different price scales. Therefore to know which price point is highest (visually) on the chart would require checking it for each series and then comparing the values.

So from the [`ISeriesApi`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi) you can get the associated Y coordinate for a price value via the [`priceToCoordinate()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#pricetocoordinate) method.

You could then get the highest coordinate by comparing the numbers obtained for the price of each series.
