### ISSUE TITLE
setCrosshairPosition() does not trigger subscribeCrosshairMove event

### ISSUE THREAD

**Issue by ChristopherJohnson25** [tradingview/lightweight-charts#1456]
setCrosshairPosition() does not trigger subscribeCrosshairMove event

Crosshair moves in case of setCrosshairPosition, it's expected that subscribeCrosshairMove event would trigger.

**Comment by SlicedSilver** [comment]
We considered this, and decided that it shouldn't trigger the `subscribeCrosshairMove`. Since your code is calling `setCrosshairPosition()`, it should also be able to call your handler for `subscribeCrosshairMove` so firing the event isn't required.
Triggering the event would actually make it more difficult to implement features like crosshair syncing between charts since it could create a stack overflow if you aren't careful.

**Comment by ChristopherJohnson25** [comment]
Ok, fair enough. Thanks @SlicedSilver!
