### ISSUE TITLE
When I use css-rotation to rotate the chart on mobile, there will be a situation where touch scrolling cannot adapt.

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [tradingview/lightweight-charts#1477]
**Lightweight Charts™ Version:** 
![image](https://github.com/tradingview/lightweight-charts/assets/8020726/ef810e84-2b20-42dc-aa31-7eb9733b999a)

Because I want the interface to be forced into landscape mode without customers flipping their phones, I use CSS rotation to achieve this rendering. However, it results in blurry rendering and chaotic touch events. What should I do?

**Comment by liuhuapiaoyuan** [comment]
Or how do I force the chart to render in full screen portrait mode?

**Comment by SlicedSilver** [comment]
The library doesn't support rotating via CSS and maintaining expected touch events. The chart appears blurry due to the CSS transform and how the browser handles rotation.

I haven't tested what comes next but you could give it a try...

Rotating an element while maintaining accurate detection of user interaction events could be challenging. The main issue is how the CSS Transform affects event coordinates. CSS transforms do not change the actual layout; they only visually manipulate the HTML elements.

You will need to tweak these event points according to the applied rotation to get the appropriate ones. But note that CSS rotation transformation could add some blurring due to subpixel rendering.

To workaround, you can rotate the parent element and leave the interactive child with inverse rotation. This way, the object visually appears rotated, but to the event system, it is still unrotated.

Here's a simple example:

```html
<div style="transform:rotate(90deg); width:200px; height:200px;">
    <div id="chart" style="transform:rotate(-90deg); width:100%; height:100%;">
        <!-- Chart Goes Here -->
    </div>
</div>
```

Regarding the blurring issue with the CSS rotate transform, there are a few workarounds you can try:

1. Forcing the browser to use GPU for rendering the transformed element.

```css
.your-element {
    transform: rotate(90deg);
    transform-style: preserve-3d;
    backface-visibility: hidden;
}
```

2. Some Chrome browsers recommend using `translateZ(0)` to fix the blur issue.

```css
.your-element {
    transform: rotate(90deg) translateZ(0);
}
```

These tips may not completely eliminate the issue, but they should certainly go some way to improving the quality of render. Different browsers might behave differently, so thorough testing is advised.

**Comment by liuhuapiaoyuan** [comment]
However, I still cannot guarantee the rotation of the touch system.

**Comment by liuhuapiaoyuan** [comment]
```html
<div style="transform:rotate(90deg); width:200px; height:200px;">
    <div id="chart" style="transform:rotate(-90deg); width:100%; height:100%;">
        <!-- Chart Goes Here -->
    </div>
</div>

```
If I use this method, then with two flips, wouldn't it visually go back to the original state?
