### ISSUE TITLE
Support for Custom Elements in Horizontal Axis for Non-Time-Based Data

### ISSUE THREAD

**Issue by jimstyler** [tradingview/lightweight-charts#1482]
I'm working on a project that requires the creation of charts with non-time-based horizontal axes, specifically for visualizing liquidity distribution. Currently, the TradingView Lightweight Charts library is primarily designed for time-series data, limiting its utility in scenarios where the x-axis represents other forms of data, such as liquidity levels, categories, or other non-time-based metrics.

I would appreciate adding a feature that allows the horizontal axis to represent custom elements, not limited to time. This enhancement would enable the creation of various charts, such as liquidity distribution charts, where the x-axis could represent different liquidity levels or categories, and the y-axis could represent the amount or volume.

The ability to customize the horizontal axis should include:

- Setting custom labels for axis ticks (e.g., different liquidity levels or categories).
- Flexibility in spacing and positioning these labels to reflect the data distribution accurately.
- Integrating this feature while maintaining the library's performance and interactivity.

This feature would significantly enhance the library's versatility, making it suitable for a wider range of data visualization tasks beyond time-series analysis.

Some example:

<img width="1072" alt="Captura de pantalla 2023-12-19 a la(s) 3 33 28 p m" src="https://github.com/tradingview/lightweight-charts/assets/1701010/0f263fa7-6ea7-4e5c-bf70-33f4c1d42017">
<img width="871" alt="Captura de pantalla 2023-12-19 a la(s) 3 33 52 p m" src="https://github.com/tradingview/lightweight-charts/assets/1701010/e87e77ad-6b48-475a-9d79-74f57b24a62c">

**Comment by SlicedSilver** [comment]
The API has recently been extended to allow customization of the horizontal scale behavior. The most common use-case would be to customise the tick marks behaviour. This would be best place to implement your desired changes without needing to modify the source code of the library.

The [createChartEx](https://tradingview.github.io/lightweight-charts/docs/api#createchartex) function should be used instead of the usual `createChart` function, and an instance of a class implementing [IHorzScaleBehavior](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/IHorzScaleBehavior) should be provided.

A simple example can be found in this test case: [horizontal-price-scale.js](https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/horizontal-price-scale.js)

**Comment by jimstyler** [comment]
Is there a live demo of horizontal-price-scale.js?

**Comment by SlicedSilver** [comment]
> Is there a live demo of horizontal-price-scale.js?
Currently there aren't any live demos, but it should be simple to create a quick demo using the code within `debug.html` and [tests/e2e/graphics/test-cases/horizontal-price-scale.js](https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/horizontal-price-scale.js)
