### ISSUE TITLE
fixRightEdge and rightOffset don't work together

### ISSUE THREAD

**Issue by srv91** [tradingview/lightweight-charts#1511]
**Lightweight Charts™ Version:** 
v4.1

I'm not sure if this is expected or a bug, but I wanted to keep the right edge fixed but also wanted to keep some blank space on the right of the chart (like a padding on the right inside the chart). For the space, I used `rightOffset` which worked as expected but if I use both `fixRightEdge` and `rightOffset` together, `fixRightEdge` overrides offset and the chart always sticks to the right.

If this is expected, is there any way I can solve this problem in an alternate way?

**Comment by SlicedSilver** [comment]
This is the expected behaviour. `fixRightEdge` means that the last data point can't be panned to the let such that there is a gap until the right edge.

You can achieve you desired behaviour by monitoring the visible range changes, checking the scroll position, and if it gets larger than your desired offset then scroll the chart back to that position. This allows the chart to have a gap on the right but to limit how big that gap can become.

```js
function myVisibleLogicalRangeChangeHandler() {
    	const pos = chart.timeScale().scrollPosition();
      if (pos > 10) {
      chart.timeScale().scrollToPosition(10)
      }
    }
    chart.timeScale().subscribeVisibleLogicalRangeChange(myVisibleLogicalRangeChangeHandler);
```

JSFiddle example: https://jsfiddle.net/msilverwood/p7Lbqe1t/

**Comment by bchpete** [comment]
This works on the right side, but if trying to implement anything for the left side (e.g. fixLeftEdge set to true or comparing logicalRange with data length) it seems to break on both sides? Any solutions to this as of yet?
