### ISSUE TITLE
`setCrosshairPosition` does not emit events to `subscribeCrosshairMove` handlers.

### ISSUE THREAD

**Issue by louisnw01** [tradingview/lightweight-charts#1519]
**Lightweight Charts™ Version:** 4.1

**Steps/code to reproduce:**

https://jsfiddle.net/L5rjph84/2/

In the jsfiddle, you can see that when moving the mouse over the chart the counter increases. However when pressing the button which calls `setCrosshairPosition`, the counter does not increase ie. no event is emitted.

**Actual behavior:**

When setting the crosshair programatically, there is no event emitted to handlers subscribed to crosshair move.

**Expected behavior:**

When calling `setCrosshairPosition`, an event should be emitted to the handlers set from `subscribeCrosshairMove`.

Thank you!

**Comment by SlicedSilver** [comment]
This is the expected behaviour and it is by design. If you code is able to call `setCrosshairPosition` then your code is also capable of calling any of your code which needs to react to crosshair move events.

If you are syncing two charts together using `subscribeCrosshairMove` and `setCrosshairPosition` then you wouldn't want `setCrosshairPosition` to emit the event because it will cause a loop and eventually a stack overflow.

setCrosshairPosition is calling a method called `setAndSaveSyntheticPosition`
https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/src/api/chart-api.ts#L336
https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/src/model/chart-model.ts#L763-L770

which specifically calls `setAndSaveCurrentPosition` with the `skipEvent` argument set to `true`
https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/src/model/chart-model.ts#L737
https://github.com/tradingview/lightweight-charts/blob/2bb415447cb3c4479a36e0c568e9a2a8f0c10439/src/model/chart-model.ts#L757-L759

**Comment by louisnw01** [comment]
Thank you Mark, appreciate the quick response. My old implementation of this would constantly unsubscribe/resubscribe the chart which is hovered over to get around the stack overflow issue.

So if i wanted `setCrosshairPosition` to emit an event, i'd need to reimplement the `setAndSaveSyntheticPosition` function with an argument of `false` for `skipEvent`?

Thanks!
Louis

**Comment by SlicedSilver** [comment]
I would suggest something along these lines:

```js
const chart = createChart(document.getElementById('firstContainer'));
const series = chart.addAreaSeries();

function doSomethingAboutCrosshairMove(price, time) {
    // do something here
}

function myCrosshairMoveHandler(param) {
    if (!param.point) {
        return;
    }
    const data = param.seriesData.get(series);
    const price = data.value !== undefined ? data.value : data.close;
    doSomethingAboutCrosshairMove(price, param.time);
}

// add your handler
chart.subscribeCrosshairMove(myCrosshairMoveHandler);

function setCrosshairPositionAndCallHandler(price, time) {
    chart.setCrosshairPosition(price, time, series);
    // call your function that is normally evoked within the move handler.
    doSomethingAboutCrosshairMove(price, time);
}

// Changing the crosshair position
setCrosshairPositionAndCallHandler(123, '2024-02-14')
```

**Comment by louisnw01** [comment]
> I would suggest something along these lines:
> 
> 
> 
> ```js
> 
> const chart = createChart(document.getElementById('firstContainer'));
> 
> const series = chart.addAreaSeries();
> 
> 
> 
> function doSomethingAboutCrosshairMove(price, time) {
> 
>     // do something here
> 
> }
> 
> 
> 
> function myCrosshairMoveHandler(param) {
> 
>     if (!param.point) {
> 
>         return;
> 
>     }
> 
>     const data = param.seriesData.get(series);
> 
>     const price = data.value !== undefined ? data.value : data.close;
> 
>     doSomethingAboutCrosshairMove(price, param.time);
> 
> }
> 
> 
> 
> // add your handler
> 
> chart.subscribeCrosshairMove(myCrosshairMoveHandler);
> 
> 
> 
> function setCrosshairPositionAndCallHandler(price, time) {
> 
>     chart.setCrosshairPosition(price, time, series);
> 
>     // call your function that is normally evoked within the move handler.
> 
>     doSomethingAboutCrosshairMove(price, time);
> 
> }
> 
> 
> 
> // Changing the crosshair position
> 
> setCrosshairPositionAndCallHandler(123, '2024-02-14')
> 
> ```

Ah great. Thanks again Mark!

Louis

**Comment by xxprzemoxx** [comment]
I jak teraz wszystko  jes OK...
