### ISSUE TITLE
Update from 3.8 to 4.1 and charts not automatically fit on update

### ISSUE THREAD

**Issue by ne0c0de** [tradingview/lightweight-charts#1569]
**Lightweight Charts™ Version:**

4.1

**Actual behavior:**

I'm using same code as I written and works well in 3.8

**Expected behavior:**

After 4.1 version update the chart is not fitting the new values that I added to chart bu .update method (not in candle stick charts and even on line series charts too)

**Comment by ne0c0de** [comment]
here it is: https://jsfiddle.net/hardc0der/Lwk9o80n/2/ @romfrancois

**Comment by romfrancois** [comment]
Thanks for providing this fiddle, very helpful.
Following our recent [release](https://tradingview.github.io/lightweight-charts/docs/release-notes#411), I would suggest adding `shiftVisibleRangeOnNewBar` to your `timeScale` object.

Otherwise and depending on your logic, you could also rely on `[scrollToRealTime](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#scrolltorealtime)` or `[scrollToPosition](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#scrolltoposition)`
