### ISSUE TITLE
How to add events to the chart along the x-axis that expand when clicked on? 

### ISSUE THREAD

**Issue by EMChloe** [tradingview/lightweight-charts#1573]
How to add events to the chart along the x-axis that expand when clicked on, like so:  
![events_TV 001](https://github.com/tradingview/lightweight-charts/assets/166934244/95ca840f-f62f-4e66-9afe-420a6a896749)

![events_expanded_TV 001](https://github.com/tradingview/lightweight-charts/assets/166934244/9c18b12d-0f33-421d-a8b1-403285dbad9e)

Is there code available to create the side bar on the right hand side of the chart with information such as the watchlist and all the charts and figures that are located in this sidebar?  

Thank you

**Comment by SlicedSilver** [comment]
These requests are outside the scope of the base library. If you are looking for these features then I can suggest looking into the [Advanced Chart library](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts). Otherwise, you could implement the time scale markers using [Plugins](https://tradingview.github.io/lightweight-charts/docs/plugins/intro). The watchlist and side panel would need to be your own UI if you are using LWC for the charting.

**Comment by EMChloe** [comment]
Thank you! @SlicedSilver
