### ISSUE TITLE
How to create a Grouped Bar Charts using lightweight-charts

### ISSUE THREAD

**Issue by ReactJS13** [tradingview/lightweight-charts#1589]
**Lightweight Charts™ Version:**  4.1.3

  From documentation, I could not able to create grouped bar charts using light-weight-charts.  

   Are we able to create grouped Bar Charts? 
      If yes, Please provide me some examples are reference area

My expectations are here

![image](https://github.com/tradingview/lightweight-charts/assets/169265799/3675bf37-eb6c-434b-a18d-ba9f4be96cdb)

@SlicedSilver - Please suggest this case

**Comment by SlicedSilver** [comment]
You can use [Plugins](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) to achieve the grouped bars.
We already have an example here: [demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/grouped-bars-series/example/) & [code](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/grouped-bars-series)

For the horizontal scale to be prices instead of time, I would suggest using the [createChartEx](https://tradingview.github.io/lightweight-charts/docs/api#createchartex) constructor which allows you to specify a different behaviour for the horizontal scale. This [test case](https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/horizontal-price-scale.js) can be used as inspiration.
