### ISSUE TITLE
PaneRendererCustomData has x=NaN in bars outside of visible range

### ISSUE THREAD

**Issue by stefda** [tradingview/lightweight-charts#1612]
**Lightweight Charts™ Version:** 4.1.4

**Steps/code to reproduce:**

1. Spin up a Custom Series projecs (called MyCustomSeries) using the provided `npm create lwc-plugin@latest` utility
2. `console.log(data)` in the created `MyCustomSeries.update` method
3. Inspect the logged data, namely the `bars` property and their `x` attribute - it is `NaN` for any bars that fall outside of the currently visible range

**Actual behavior:**

The `bars.x` property in the `PaneRendererCustomData` provided through the `MyCustomSeries.update` method is `NaN` in bars outside of the visible range.

**Expected behavior:**

The `bars.x` property in the `PaneRendererCustomData` provided through the `MyCustomSeries.update` method is set with the correct `x` value, including for bars outside the visible range. The `x` will be negative for values before the start of the visible range and greater than the media width of the visible pane for any bars beyond the visible range.

**Screenshots:**

![image](https://github.com/tradingview/lightweight-charts/assets/212397/fc783f10-e902-44d4-80c5-3145f2a5455e)

**Use case**

I am creating a renderer to draw custom series that have a price value at each bar (and that value may be drawn as a point or as a k-line), and some some of the points are connectes with a line (think open position point and realized PNL point). The start/end of a line may fall outside of the visible range when scrolling through the chart, but as the `bar.x` value is NaN outside the visible range, I have no way of determining the correct placement of those points in such scenario.

I would like to know if the issue described above is indeed a bug or a feature. If it's the latter then it might be useful to discuss this case in the [CustomBarItemData](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/CustomBarItemData) docs.

**Comment by stefda** [comment]
I have a feeling it might be related to the issue described [here](https://github.com/tradingview/lightweight-charts/issues/1605).

**Comment by SlicedSilver** [comment]
Providing `NaN` values is the expected behaviour. It is slightly quicker to generate the rendering data, and also makes it easier to write the renderer code such that it is only drawing what is visible. However if you need to know what the offscreen values would be then it is possible to calculate it.

The spacing between each `x` coordinate is consistent, and is defined by the `barSpacing` of the timescale. The [`PaneRendererCustomData`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PaneRendererCustomData) which is provided to the custom series' `update` method contains this `barSpacing` value. So where you are currently reading the `bars` array, a sibling property provides the spacing.

It would be quite simple to calculate what the offscreen `x` values would be by using this information. For example, if you have a `barSpacing` of 6 of an list of x values like this: `[NaN, NaN, -2, 4, 10, 16, NaN]` then you subtract or add the barSpacing consecutively to get: `[-14, -8, -2, 4, 10, 16, 22]`

I would recommend that you calculate such values required for the renderer within the 'View' but you can do this within the renderer as well (no forced rules on this).

**Comment by stefda** [comment]
Thanks, got it. What you're suggesting is exactly what I ended up doing. Good to get a validation!
