### ISSUE TITLE
Updating tick data on the daily time frame

### ISSUE THREAD

**Issue by x945** [tradingview/lightweight-charts#1624]
Official examples show the tick updates on the same time frame, as a result, the bars are moving to right whenever new data is received. However, on higher time frames, the bar needs to be stationary while latest close price is being updated. Any ideas on how to achieve that?

https://jsfiddle.net/TradingView/yozeu6k1/

**Comment by SlicedSilver** [comment]
You can use the [`series.update()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#update) method to:
- Add a new latest data, (timestamp newer than last time stamp)
- or update the values for the current last data point (timestamp matches the timestamp of the last value)

Here is an example showing the updating of both existing bars and adding new bars of data: https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates

**Comment by x945** [comment]
> You can use the [`series.update()`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#update) method to:
> 
>     * Add a new latest data, (timestamp newer than last time stamp)
> 
>     * or update the values for the current last data point (timestamp matches the timestamp of the last value)
> 
> 
> Here is an example showing the updating of both existing bars and adding new bars of data: https://tradingview.github.io/lightweight-charts/tutorials/demos/realtime-updates

I use `setLastDate(dps.slice(-1)[0].time);` to get the last date from the series array, and use the `lastDate` value to update the current last data point. The issue is the bars keep moving to the right with the current last date unchanged.

**Comment by Arriccccc** [comment]
Have you solved the problem yet? How was it solved, I'm being stuck with this problem, it make me crazy

**Comment by lseven007** [comment]
yes,when u use update(data),the data is did updated, but the time is still the old, the time will never update with new updated data

**Comment by SlicedSilver** [comment]
Perhaps there is some confusion on what the 'time' for a data point means. In financial charts, the time represents the start of the data point (aka candlestick). So for example, if you are displaying data at a 1hr resolution and send data updates at 2:00, 2:05, 2:10, etc... then all those would still have the same timestamp on the time scale of 2:00 because they are part of the same data point (all price changes between 2:00.000 and 2:59.999).

This might explain the confusion of why the time value doesn't seem to change.
