### ISSUE TITLE
Stackedbar chart is faded when zoom out 

### ISSUE THREAD

**Issue by QuachTrienHuy1107** [tradingview/lightweight-charts#1717]
**Lightweight Charts™ Version:** 
4.1.3

**Actual behavior:**
Hello everyone, 
I am using the stacked bar chart and have copied the code from  `plugin-examples` folder ( in this [link](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) ).

The chart renders data correctly; however, it fades when I zoom out.

**Expected behavior:**
When zooming in or out, the stacked bar chart remains clearly readable without any fading.

**Screenshots:**

https://github.com/user-attachments/assets/83cfe907-2fab-424c-89d6-add4f17d3352

Any guidance on resolving this would be greatly appreciated.

**Comment by SlicedSilver** [comment]
This is the expected behaviour of the plugin as it is matching the rendering approach of the [histogram](https://tradingview.github.io/lightweight-charts/docs/series-types#histogram) series types.

It is using the approaches mentioned in this guide: [Best Practices for Pixel Perfect Rendering in Canvas Drawings](https://tradingview.github.io/lightweight-charts/docs/plugins/pixel-perfect-rendering)

Since it is a plugin, you are welcome to create your own version of the series by using the provided code, and then making your modifications to the rendering code. For example, rather using the code mentioned here: [Full Bar Width Calculations](https://tradingview.github.io/lightweight-charts/docs/plugins/pixel-perfect-rendering/widths/full-bar-width)
