### ISSUE TITLE
Support for gradient color for line and area series

### ISSUE THREAD

**Issue by pinal-knoxpo** [tradingview/lightweight-charts#185]
Add support for gradient colour in line, candle

**Comment by timocov** [comment]
How you'd expect to see gradient color? From top to bottom or from left to right? Can you please provide a little bit more info: screenshots, link to other charts where you've seen that?

**Comment by pinal-knoxpo** [comment]
Thanks for prompt reply. My requirement is Fill area chart with gradient based on line gradient.
Something like 
![gradient](https://user-images.githubusercontent.com/47237425/63568813-5695cb80-c594-11e9-9f01-60f74fd2ee6c.jpg)

Direction will be any, right now I want left to right, but ideally it accept both direction.
And, Set gradient colour in each candle also for up & down also accept colour in rgba() format. 
It is gentle request.

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following example:
	•	[Background Shade Series](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/background-shade-series): This example demonstrates how to achieve a shaded background for a custom series. [Demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/background-shade-series/example/)

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
