### ISSUE TITLE
Line series with starting x-value out of viewport is not rendered correctly

### ISSUE THREAD

**Issue by jimeney** [tradingview/lightweight-charts#197]
An earlier issue was closed relating to the non-display of a line series where the starting x-value was out of the viewport.

In 1.1 this has been somewhat cured, however there appears to be an issue in rendering/scaling when the start X/Y is outside of the viewport still:

Number of bars presented > number of bars the line series cover
![image](https://user-images.githubusercontent.com/4056227/64426272-0cd5d680-d0a6-11e9-99b8-31576ca8f179.png)

Live example:
https://www.chartex.pro/chartviewerinline.html?symbol=BINANCE:BTC/USDT&timeframe=60&trendlines=1&w=1000&barstoshow=300

Number of bars presented < number of bars the line series covers
![image](https://user-images.githubusercontent.com/4056227/64426321-2840e180-d0a6-11e9-84a3-0a87fcea9b5f.png)

Live example:
https://www.chartex.pro/chartviewerinline.html?symbol=BINANCE:BTC/USDT&timeframe=60&trendlines=1&w=1000

**Comment by jimeney** [comment]
Related / previous issue: https://github.com/tradingview/lightweight-charts/issues/116

**Comment by kirchet** [comment]
> however there appears to be an issue in rendering/scaling when the start X/Y is outside of the viewport still

Can you describe it in more details? I don't see any issues in rendering/scaling. Also it would be better if you created the examples on JSFiddle, it's not always obvious what data you're passing to the library

**Comment by timocov** [comment]
@jimeney the problem is with the top line, am I right? If so, I hope this happens because there is no other data between the leftmost point of the line and the leftmost bar of the candlestick series. `lightweight-charts` does not approximate points in the future/past, so in this case this point is just 1 visual point left. You can try to put empty bars to "extend" time scale.

Also, if you have a suggestion how to make built-in solution for that - feel free to leave it here.
