### ISSUE TITLE
Add option for price axis overlay the pane

### ISSUE THREAD

**Issue by nikitamarcius** [tradingview/lightweight-charts#208]
Add an option so that the price bar is on top of the chart.

![11](https://user-images.githubusercontent.com/10992863/64872670-47181880-d650-11e9-8086-0f988dbaa59c.png)

**Comment by timocov** [comment]
That's a good suggestion, thank you. I believe we can add new positions for price axis something like `overlay-left` and `overlay-right`.

**Comment by chongruei** [comment]
any update?

**Comment by tomsnep** [comment]
+1

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following example:
	•	[Overlay Price Scale](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/overlay-price-scale): This example demonstrates how to achieve x, y, and z. [Demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/overlay-price-scale/example/)

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
