### ISSUE TITLE
Possibility to have multiline text in watermark

### ISSUE THREAD

**Issue by ws420** [tradingview/lightweight-charts#265]
Is it possible to have a line break in the watermark so I can have 2 lines of text?

Thanks

**Comment by timocov** [comment]
Currently I don't think that it'll work correctly because we don't split passed line into separate lines before pass them to the renderer [here](https://github.com/tradingview/lightweight-charts/blob/2c78462e4190dee0fd59ba0708cb6311572c3897/src/views/pane/watermark-pane-view.ts#L56-L64). But I think it shouldn't be really hard to fix it.

**Comment by SlicedSilver** [comment]
By using a transparent background colour on the chart, you can manually create a more complex watermark. Here is an example: https://tradingview.github.io/lightweight-charts/tutorials/how_to/watermark

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples:
	•	[Image Watermark](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/image-watermark): This example demonstrates how to draw a watermark on the chart. [Demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/image-watermark/example/)
	•	[Anchored Text](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/anchored-text): This example showcases how to draw text on the canvas. [Demo](https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/anchored-text/example/)

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
