### ISSUE TITLE
Candlestick shape customization

### ISSUE THREAD

**Issue by Snitovets** [tradingview/lightweight-charts#291]
I'm interested in implementing candlestick enhanced customization:

**1.** Rounded candlestick body.
**2.** ctx.lineCap = 'round' candlestick shadow.

Attaching image from my svg-chart project:
![image](https://user-images.githubusercontent.com/38501107/71446191-4865e080-2729-11ea-838b-f77b7a77d238.png)

**Comment by timocov** [comment]
Hi,

thanks interesting beautiful suggestion. 

> Rounded candlestick body.

It might affect performance, because instead of `fillRect` to draw candlestick we need to use path (lineTo, moveTo, arc, etc) to draw one candle. I haven't number right now, but we need to really worry about that here. We can try to do it with noting that rounded candlesticks might reduce fps/ux.

> ctx.lineCap = 'round' candlestick shadow.

It works for stroking, but currently (and will be in the future I believe) wicks drawn with `fillRect` due 1) performance and 2) pixel-perfect. I don't think that we'll decide to use stroking instead, so we have only 1 solution here - use paths... That's all is a bit ambiguous (at least for me). Yeah, we need to measure perf before make any change here.

**Comment by Snitovets** [comment]
Thank you for detailed response.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
