### ISSUE TITLE
Incorrect display of the price scale.

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#341]
Good day.

Incorrect display of the price scale. why not display the required number of decimal places. only two characters are displayed

jsfiddle:  https://jsfiddle.net/cpqbx78n/

**Comment by timocov** [comment]
It looks like we [use price scale's formatter instead of series' one](https://github.com/tradingview/lightweight-charts/blob/e0e1e2c10d634745187179abf86a5288a14998e9/src/model/series.ts#L202) to format prices (and price scale's formatter is formatter of the main/first series on the price scale). I'm not sure whether it's correct of not.

@eugene-korobko what do you think?

**Comment by Altyair** [comment]
in this case https://jsfiddle.net/cpqbx78n/1/ 
the price scale looks correct, but the line is under the candles

In this case: https://jsfiddle.net/cpqbx78n/1 / 
the line above the candles is what I need, but the price scale is not correct.

I need the line to be displayed above the candles and the price scale to look correct.

**Comment by timocov** [comment]
> the price scale looks correct, but the line is under the candles

If so, try to set the same `priceFormat` to all series you have.

**Comment by Altyair** [comment]
thanks
