### ISSUE TITLE
Allow the use of Timezone on a chart

### ISSUE THREAD

**Issue by HighBreedTech** [tradingview/lightweight-charts#359]
"timezone": 'America/New_York'

or

"timezone_offset": GMT+01:00

 this will be good to solve Time to work with exactly client time, or do we have this active already?

const chart = LightweightCharts.createChart(document.getElementById('trade-line-chart'), {
    width: 1800,
    height: 800,
    timezone: 'America/New_York',

});
i am hoping this could be great, and please if you have related solution i am here please help me.

@timocov
@nikitamarcius

**Comment by timocov** [comment]
> or do we have this active already?

No, we don't have it.

> "timezone_offset": GMT+01:00

It won't be worked because to work with timezones you need to know _timezone's name_, because, for instance, some of timezones has DST, some of them has different offsets in the history even if at the moment they have the same offset (e.g. GMT+1).

If you want to just add some constant offset to time you can add it from your side.

Actually browsers (or even JavaScript?) doesn't support well timezones in dates so we don't plan to work with them.

If you really wish to have timezones on the chart, you can either implement it from your side and pass "corrected" values to the chart (actual UTC time + tz offset _for that_ time) or use charting library, which has built-in support for the most timezones and is able to handle them correctly.

**Comment by HighBreedTech** [comment]
Ok thanks.

**Comment by HighBreedTech** [comment]
Hello Famz Finally i solve this problem by writing a JS function code like to make he timezone time and this solved my problem without needing to set Timezone to graph if you need the solution i will post it here just make a request and i will send it here.

**Comment by nikitamarcius** [comment]
@HighBreedTech u can create example on JSFiddle and then add link to  https://github.com/tradingview/awesome-tradingview

**Comment by vishnug1995** [comment]
> @HighBreedTech u can create example on JSFiddle and then add link to https://github.com/tradingview/awesome-tradingview

can you post the solution

**Comment by vishnug1995** [comment]
> Hello Famz Finally i solve this problem by writing a JS function code like to make he timezone time and this solved my problem without needing to set Timezone to graph if you need the solution i will post it here just make a request and i will send it here.

can you post the solution ?

**Comment by edinsoncs** [comment]
The same thing happens to me, I'm using v18

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/v3.7.0/docs/time-zones.md.

I just wanted to note that lightweight-charts and charting library (or TradingView's Advanced Charting Widget) are completely different products and please respect everybody in this repo and do not mix these products up here. This issue tracker and the repo are about `lightweight-charts` product only.

Also, I'm going to lock this issue since it becomes off-topic.
