### ISSUE TITLE
How to present multiple data in one time unit？

### ISSUE THREAD

**Issue by Usey95** [tradingview/lightweight-charts#415]
I want to present something like [this](https://www.chartjs.org/samples/latest/charts/bar/multi-axis.html), instead of overlaying the data, separate them evenly. Is there anyway to do it ?

**Comment by timocov** [comment]
Hm, looks like I don't really get your case. What's the difference between your link and adding histogram series to the lightweight-charts?

**Comment by Usey95** [comment]
> Hm, looks like I don't really get your case. What's the difference between your link and adding histogram series to the lightweight-charts?

Ha, I mean right now if I add several histogram series which have the same dates but different values to lightweight-charts, the rectangles will overlay each other. What I want to achieve is presenting these rectangles separately.

**Comment by timocov** [comment]
What price scales they used? Are they overlay?

**Comment by Usey95** [comment]
> What price scales they used? Are they overlay?

The price scales are the same, I draw a [picture](https://processon.com/chart_image/5ea2ddcb1e085346f71c95be.png)

**Comment by timocov** [comment]
Ah, I see. I'm afraid the aim of the project is a bit different and we won't plan to implement suck kind of histograms.

**Comment by leeoniya** [comment]
@timocov since this is not something you guys plan to work on, i hope you don't mind me suggesting an alternative [1], since we have very similar performance-centric goals and actually quite a bit of overlap in libs. uPlot even has a basic candlestick demo [2] :)

the bars demo [3] does pretty much @Usey95 is asking for (but doesnt do a most of what lightweight-charts does). it was actually not too hard to distribute each datapoint horizontally. feel free to steal the logic from my repo for lightweight-charts, (if it's feasible).

lightweight-charts looks cool and i'd like to include it in my 166k datapoint benchmark [4] to see how it does. cheers!

[1] https://github.com/leeoniya/uPlot
[2] https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html
[3] https://leeoniya.github.io/uPlot/demos/multi-bars.html
[4] https://github.com/leeoniya/uPlot#performance

**Comment by Usey95** [comment]
@timocov it's ok, I'll do it myself.
@leeoniya amazing project, see what can I learn from it, hopefully one day I can do some contribution to it.
Thanks a lot guys.😘
