### ISSUE TITLE
How to show hide series on chart with switcher

### ISSUE THREAD

**Issue by Winthan** [tradingview/lightweight-charts#42]
is there any example with switcher for multiple series to show and hide each series?

**Comment by eugene-korobko** [comment]
You can just remove one series and add new one.
[Here](https://jsfiddle.net/TradingView/qrb9a850/) is a sample

**Comment by timocov** [comment]
> You can just remove one series and add new one.

I believe there should be a method to hide a series because of perf (hide is faster than remove/add series).

**Comment by timocov** [comment]
Hey @Winthan,

after research on hiding the series we found a some issues which blocks us to implement visibility for series (e.g. issues in percentage mode, in autoscale mode, UX and so on).

But also we've look at removing/adding series and we noticed that it isn't much slow and shouldn't reduce performance a lot.

So, I believe you can use removing/adding series for now instead of hide/show it. If you'll face with much reducing of the performance, please let us know.
