### ISSUE TITLE
Scaling via mouse click and drag doesn't work if chart is inside shadow root.

### ISSUE THREAD

**Issue by trading-peter** [tradingview/lightweight-charts#427]
**Lightweight Charts Version:** 2.0.0

**Steps/code to reproduce:**

Put any chart inside a custom html element using the custom element api of modern browsers.

**Actual behavior:**

If a chart is located inside the shadow root of a custom element scaling time or price bar with the mouse (click + drag) won't work

**Expected behavior:**

Scaling should work as normal

**Screenshots**

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Can you provide a link where I can see such behaviour?

**Comment by pkaske** [comment]
Here put together the most simple demo possible. It's using the web components api and the shadow dom api available in all modern browsers. This is also how frameworks like lit-element and polymer render components internally.

https://codesandbox.io/s/frosty-glade-wb9nq?file=/src/index.js

**Comment by timocov** [comment]
It seems that the reason is the browser sends an event about `mousedown` to `document` with `target` as `shadow-root` rather than `canvas`, then [the check](https://github.com/tradingview/lightweight-charts/blob/96f10d7b20e9f956ab0aadf993f88f827099e6c8/src/gui/mouse-event-handler.ts#L358) fails and we generate "outside click" event.

**Comment by timocov** [comment]
And it seems that there is no a way to detect to what element exactly the event was (original target):

![image](https://user-images.githubusercontent.com/3112183/85378033-ac375d80-b542-11ea-84d7-88267850d9ae.png)

`path` prop seems like something Chrome-specific. @trading-peter maybe you have an idea how to handle this correctly? This code tries to detect outside clicks, we subscribe on click events in the document and check whether an event is for our container or not. If it's not - that's outside event. The problem is that `target` in the event is the root element rather than internal element.

**Comment by timocov** [comment]
Seems I found solution for that.

**Comment by trading-peter** [comment]
You can use https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath. That will give a list of all elements the event bubbled through. Through shadow roots.

**Comment by trading-peter** [comment]
So I guess `event.composedPath()[0]` is what you need.

**Comment by timocov** [comment]
Wow, thanks! That's actually what we need there instead of dancing with `shadowRoot` :)

**Comment by trading-peter** [comment]
Happy to help if I can :)
