### ISSUE TITLE
Disabling/enabling scaling axis for both price and time

### ISSUE THREAD

**Issue by yusufsahinhamza** [tradingview/lightweight-charts#440]
**Is your feature request related to a problem? Please describe.**

It's not possible to disable scaling axis for only price or time.

**Describe the solution you'd like**

Instead of disabling/enabling scaling axis like that:

```
chart.applyOptions({
    handleScale: {
        axisPressedMouseMove: false
    }
});
```

We can seperate scaling axis to options for only price or time like that:

```
chart.applyOptions({
    handleScale: {
        priceAxisPressedMouseMove: false,
        timeAxisPressedMouseMove: true
    }
});
```

**Additional context**

I would like to create an PR for that if it's okay.

**Comment by timocov** [comment]
Sounds good. To avoid breaking changes, let's do in the following way:

```
chart.applyOptions({
    handleScale: {
        axisPressedMouseMove: {
			time: false,
			price: false,
		},
    },
});
```

In this case, we can correctly handle `axisPressedMouseMove: true`/`axisPressedMouseMove:false` and will set `time` and `price` options accordingly. Internally we could don't worry about boolean values, because they should be converted on API level (the same as shorthand `handleScale: true` for instance).

Thus, `axisPressedMouseMove`'s type should be changed from `boolean` to `boolean | AxisPressedMouseMoveOptions`, where `AxisPressedMouseMoveOptions` is `{ time: boolean; price: boolean; }`. Internally (in price and time axis widgets) we should use the only `AxisPressedMouseMoveOptions` and don't even know that there might be a `boolean` value at all.

Let me know if you have any questions.
