### ISSUE TITLE
tradingview lightweight-charts time axis strange behaviour

### ISSUE THREAD

**Issue by masterchart** [tradingview/lightweight-charts#483]
Device: Windows 10
Broswer: Chrome
Description: I need to display this chart:

![issue](https://user-images.githubusercontent.com/14291772/84872066-ab558600-b081-11ea-846a-feff5d71c7d6.PNG)
```js
var chart = LightweightCharts.createChart(document.body, {
  width: 600,
  height: 300
});
chart.applyOptions({
  timeScale: {
    timeVisible: true,
    secondsVisible: true,
  },
  localization: {
    locale: 'it',
  },
});
var areaSeries = chart.addAreaSeries({
  topColor: 'rgba(21, 146, 230, 0.4)',
  bottomColor: 'rgba(21, 146, 230, 0)',
  lineColor: 'rgba(21, 146, 230, 1)',
  lineStyle: 0,
  lineWidth: 3,
  crosshairMarkerVisible: false,
  crosshairMarkerRadius: 3,
});

areaSeries.setData([{
  "time": 905299200,
  "value": 0.25
}, {
  "time": 918781200,
  "value": 0.0
}, {
  "time": 935952000,
}, {
  "time": 965952000,
  "value": 0.25
}, {
  "time": 983408400,
  "value": 0.15
}, {
  "time": 985050000,
  "value": 0.0
}, {
  "time": 1152835200,
  "value": 0.25
}, {
  "time": 1172019600,
  "value": 0.5
}, {
  "time": 1225414800,
  "value": 0.3
}, {
  "time": 1229648400,
  "value": 0.1
}, {
  "time": 1286236800,
  "value": 0.1
}, {
  "time": 1454029200,
  "value": -0.1
}, {
  "time": 1454288400,
  "value": 0.0
}]);
```

but if you look at the time axis at 2000-2006 and 2006-2008, space used is more or less the same so the chart look strange, how can I fix this issue without any change to the json?

Thanks 

Luca

**Comment by timocov** [comment]
Closed in favour to https://stackoverflow.com/questions/62328580/tradingview-lightweight-charts-time-axis-strange-behaviour.

**Comment by benelliott** [comment]
Hi @timocov, I am currently evaluating lightweight-charts for use in an app that renders a high volume of events to a time series chart. The intervals between these events are inconsistent (an example could be usage log messages). My initial implementation has the prolem described in this issue where the x-axis timescale is improperly scaled due to these inconsistent intervals.

Can I confirm that the only solution to this problem is to iterate through all the data, find the minimum time distance between points, then iterate back through all the data and pad accordingly?

For example, say I have a series of events that happen approximately 1 hour apart. Then for some reason, two events happen within 0.05 seconds of each other. Do I need to go back through the entire series and add a whitespace entry for every 0.05 second increment?

If this is correct then this will unfortunately be a dealbreaker for using lightweight-charts in my project.

Thanks.
