### ISSUE TITLE
Reducing precision doesn't update price scale width

### ISSUE THREAD

**Issue by SuperPenguin** [tradingview/lightweight-charts#550]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

```ts
series.applyOptions({
    priceFormat: {
        precision: 6,
        minMove: 0.000001,
    },
});
```

and after a while, run

```ts
series.applyOptions({
    priceFormat: {
        precision: 2,
        minMove: 0.01
    }
});
```

**Actual behavior:**

Price scale width doesn't adapt to new width.

**Expected behavior:**

Price scale width should adapt to new width

**Screenshots:**

![8dE0YFFdMh](https://user-images.githubusercontent.com/1574722/91115849-53f11900-e6b5-11ea-8908-363f315f8572.gif)

**CodeSandbox/JSFiddle/etc link:**

Repo link https://github.com/SuperPenguin/lightweight-charts-example/tree/master/src/charts-button

Current workaround is to resize chart using applyOptions to fix price scale width

**Comment by timocov** [comment]
I believe it's done [somewhere here](https://github.com/tradingview/lightweight-charts/blob/2ae4ac58cd7967436aa50b5ef0290a7ff284fe02/src/gui/price-axis-widget.ts#L607-L629)...

I think that it's done to avoid "infinite loop" of changing price scale width from smaller to bigger and back: let's say we have a price scale with 100px width, then you move visible range for 1 bar to the history which might lead to recalculate the price range (due auto scaling), the new data might increase count of visible digits by 1 so now width of the price scale should be 120px but this forces to recalculate with of the pane which changes the visible range and hides the bar you just scrolled to, then the price scale width change back to 100px which leads changing visible range and here we have a loop 🙂 That's why we didn't change the width back to smaller one.

If you have any ideas how it could be fixed in other way and decreasing width as well - please let us know :)

**Comment by JessseG** [comment]
Was this ever fixed? Im also applying this ```applyOptions ``` command dynamically but the chart won't update. I'm working vith version 3.3

Here's the full command. The chart doesn't respond.

**Comment by thanhlmm** [comment]
@timocov Could we run the set axis width 2 times? Based on your example, on the first time it set the width to 100px. Then we check again if the new optimal width is bigger than 100px, then we set it to the new width, if not, just let it be

**Comment by timocov** [comment]
https://jsfiddle.net/em8hz9xd/
