### ISSUE TITLE
Drop restriction for min bar spacing value

### ISSUE THREAD

**Issue by ch4rlesyeo** [tradingview/lightweight-charts#558]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**
https://jsfiddle.net/zon02dfk/4/

**Actual behavior:**
Chart doesn't fit all area series data when there are more than a 700 data points in mobile view.

**Expected behavior:**
Chart should fits all area series data.

I have a use case where i need to display 20 mins of data by second, therefore there will be 1200 (20 * 60) of data points where i need to fit in the chart given limited amount of width in mobile view.

**Comment by timocov** [comment]
Related to #252, #229, https://github.com/tradingview/lightweight-charts/issues/251#issuecomment-552865393.

Did you see https://github.com/tradingview/lightweight-charts/issues/229#issuecomment-554355411? As I said there, it could be tricky to display data in that way (if we disable that limit) and quite possible that you even don't expect to see the result you'll see if you remove [the limitation](https://github.com/tradingview/lightweight-charts/blob/master/src/model/time-scale.ts#L33), because we can't guarantee that the result will be the same all time and it will be "data is displayed somehow". It's possible that we need to add an option for that to change this limit, but I want to know that everybody will understand all side-effects of that.

**Comment by ch4rlesyeo** [comment]
Yeah can see where you're coming from, i'm aware that there is a limit where our vision can handle.

I'm up for the removal of limitation, at least we allow users to zoom out to an extreme limit where they can no longer understand the chart anymore they would eventually zoom back in.

**Comment by kmecpp** [comment]
I agree with the above as a end goal. As for dealing problems with rendering I would much rather have the option to set min spacing now as a temporary solution even if it breaks at extreme values rather than wait until some perfect solution is found and implemented

**Comment by shimikano** [comment]
We're using the `PriceScaleMode.Percentage` mode for the `rightPriceScale`.

In a chart that has too many data points such that the `MinBarSpacing` restriction prevents users from seeing the entirety of the chart, this means that there is no way to see the percentage change ("performance") of the entire data range: If you pan towards the beginning, you don't see the right hand part, if you pan towards the end, the `PriceScaleMode.Percentage` mode causes the performance to be calculated from the beginning of the visible range, not from the beginning of the entire data range (which it's supposed to of course).

We experimentally set `MinBarSpacing` to zero and it didn't cause rendering or performance trouble (we have roughly 8000 data points to render in a chart of a width of 1800px).

Hence, as @ch4rlesyeo and @kmecpp suggested, I'm also in favor of allowing to override the default `MinBarSpacing` "at the user's own risk" as a quick fix for the time being.

Thanks for your consideration.

**Comment by timocov** [comment]
Ok, let's just allow to override that limit via options in https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options (something like `minBarSpacing`), by default let's set it to the current default value (0.5 at the moment).

PRs are welcomed (please don't forget about tests).
