### ISSUE TITLE
Time axis hour only

### ISSUE THREAD

**Issue by jerssonMA** [tradingview/lightweight-charts#560]
It is possible to show only the time on the time axis, I am reviewing the documentation but it is not clear to me how to pass and format the date so that only the time is seen.

Can I see that it should be passed as a timestamp but how do I indicate that it only shows the time?

**Example**
![image](https://user-images.githubusercontent.com/65183481/92041717-60711380-ed3e-11ea-8c9d-19d04d5d66be.png)

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options `tickMarkFormatter` option.

**Comment by giladt** [comment]
hey @timocov , the link you have provided is broken (as well as many others in the docs). Is there any updated location to find it the docs?

**Comment by timocov** [comment]
> Is there any updated location to find it the docs?

@giladt please refer to a tag instead of `master` branch. For example for https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#time-scale-options you use use https://github.com/tradingview/lightweight-charts/blob/v3.6.1/docs/time-scale.md#time-scale-options instead. We're in the process of creating a website for our docs (you can check current state out here https://tradingview.github.io/lightweight-charts) so that's why links don't work any more.
