### ISSUE TITLE
Candlestick chart won't render candlesticks while loading around 5000 - 10000 candles

### ISSUE THREAD

**Issue by markverkiel** [tradingview/lightweight-charts#563]
**Lightweight Charts Version: 3.1.5** 

**Steps/code to reproduce:**
Easiest way to reproduce is to call `candleStickSeries.setData([candles])` with 5000 - 10000 candles. 
I used the example from JSFiddle as base to reproduce this problem, making sure this isn't a config problem on my end.

**Actual behavior:**
Chart starts spamming `"Value is null"` errors in the developer console and won't render the candlesticks.

**Expected behavior:**
Longer wait time since the chart is loading a large amount of data, but render all the candlesticks.

**Screenshots:**
![image](https://user-images.githubusercontent.com/4355302/92176576-073cd900-ee3f-11ea-8162-3854843d123a.png)

**CodeSandbox/JSFiddle/etc link:**
https://jsfiddle.net/markverkiel/j3syf4dr/4/

**Comment by matortheeternal** [comment]
Just got this error as well, stepping through the stack trace I see `SeriesCandlesticksPaneView.prototype._internal__createRawItem` calling `colorer._internal_barStyle(time);`, which then calls `this._private__findBar(barIndex, precomputedBars)` which returns `null` because `precomputedBars` wasn't passed around (and doesn't exist yet?)

I'm going to try testing with a smaller number of bars to see if that changes the result.

**Comment by matortheeternal** [comment]
I believe I found the problem.  The `lowerbound` function, which is a binary search function, uses the `_internal_index` property when performing the binary search.  This property is incorrectly set to `0` for items 999 through 1082 (in my array).  I'm going to try to figure out how this property is assigned so I can see if I can figure out why these values are set incorrectly.

**Comment by matortheeternal** [comment]
I [added some code to your fiddle](https://jsfiddle.net/hds4wa2q/) to check if you had duplicate times in your data, and you do.  The following times were duplicated:

```js
["1593663300", "1593664200", "1593665100", "1593666000", "1593666900", "1593667800", "1593668700", "1593669600", "1593670500", "1593671400", "1593672300", "1593673200", "1593674100", "1593675000"]
```

Also your times aren't integers, which is kind of weird, you should use Math.round to make them into whole numbers instead of floating point.

**Comment by markverkiel** [comment]
Thanks for the fast feedback much appreciated!
I've tested this against my own data and it seems that duplicate candles are indeed the problem for this issue.

Since this is currently breaking the chart, maybe it's an idea to cancel the rendering and throw an error for duplicate time entries? Or throw a warning indicating that the data consist duplicate entries.

**Comment by timocov** [comment]
> Since this is currently breaking the chart, maybe it's an idea to cancel the rendering and throw an error for duplicate time entries? Or throw a warning indicating that the data consist duplicate entries.

See #315

**Comment by timocov** [comment]
I guess the issue is solved now?

**Comment by jazoom** [comment]
It seems this error can mean many different things. I had no duplicates and only 4 items in the array. The timestamp was an integer. I couldn't work out why it infinitely spewed out "Value is null", since that error message means nothing, and is actually deceptive in this case. Debugging with Firefox was difficult because the infinite loop kept hanging the browser. It was a bit easier in Chrome.

In my case it was simply that the order of the items in the array was most recent to least recent. Reversing it fixed the problem.

Maybe this will help someone else.

**Comment by markverkiel** [comment]
> I guess the issue is solved now?

Yes this issue is resolved, closing it. 
This won't cause confusion anymore when issue #315 is finished.
