### ISSUE TITLE
set series visibility to false has no effect

### ISSUE THREAD

**Issue by RubberArchind** [tradingview/lightweight-charts#589]
**Lightweight Charts Version:** 
https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js
**Steps/code to reproduce:**
```
candleSeries.applyOptions({
        visible: false,
    });
```

**Actual behavior:**
I tried to set the series visible option to false yesterday but the candles still appear on the chart

**Expected behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/35050952/95535274-3d5b1300-0a12-11eb-880f-389937c04421.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by RubberArchind** [comment]
```
candleSeries.applyOptions({
        visible: false,
    });
```
This is what i wrote

**Comment by timocov** [comment]
Did you see in what version this feature was added?

**Comment by RubberArchind** [comment]
I don't know but it's in the [documentation](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md) .

**Comment by timocov** [comment]
Why don't you look at documentation for the version you use? `master` branch is for development and does nothing for releases (patch fixes might be even out of the main commits tree, because they might be from release branch).

https://github.com/tradingview/lightweight-charts/blob/v3.1.5/docs/series-basics.md

**Comment by RubberArchind** [comment]
oh I'm sorry, it's my foolishness :(
