### ISSUE TITLE
Option to disable current price label

### ISSUE THREAD

**Issue by thisconnect** [tradingview/lightweight-charts#623]
**Is your feature request related to a problem? Please describe.**

I am trying to setup a very minimalistic chart, only pricescale+timescale+arealine, I plan to show current price outside/before  the chart, unfortunately I could not find a way to disable the current price on the pricescale.

![Screen Shot 2020-11-17 at 12 39 44 PM](https://user-images.githubusercontent.com/546900/99386356-a320a180-28d2-11eb-9cce-eabd1c36f2a9.png)

**Describe the solution you'd like**

Any way to disable the priceLabel on the PriceScale, i..e `priceLabelVisible: false`

**Additional context**

minimal example without priceline, but the pricelabel is still on the pricescale https://jsfiddle.net/vg1bn0os/1/

**Comment by timocov** [comment]
Please look at [our docs](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#price-labels) first.

Let's keep this issue tracker for features and bugs, rather than questions. For questions please use [stackoverflow](https://stackoverflow.com/questions/tagged/lightweight-charts) and [discord](https://github.com/tradingview/lightweight-charts/issues/241).
