### ISSUE TITLE
the method < chart.timeScale().setVisibleLogicalRange() > doesn't work

### ISSUE THREAD

**Issue by grayson-liu95** [tradingview/lightweight-charts#650]
**Lightweight Charts Version:**  3.2.0

**Steps/code to reproduce:** I just want to set a visible range, and I write code as following:
*****************
   _this.chart.timeScale().setVisibleLogicalRange({
        from: 100,
        to: 1373
      });
***************

**Actual behavior:** I print the result on chrome console, and it shows:
******************
{ from: 1311.6666666666667, to: 1373 }
*****************
So the action to set the range is useless. How can I solve this problem?

**Expected behavior:** The result is expected as what I set with the timeScale api.

**Screenshots:**
![image](https://user-images.githubusercontent.com/67615599/101976910-d9a8cc80-3c84-11eb-8d7e-b52d9a5093cb.png)

![image](https://user-images.githubusercontent.com/67615599/101976881-8fbfe680-3c84-11eb-9e30-383019140425.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Changing visible range affects some other dependent things (like visible price range for example), and they on other hand might affect visible range (for instance when width of the price axis is changed). To avoid unnecessary recalculations the library doesn't apply changes right after the call - it postpones all changes until the next animation frame is happened (`requestAnimationFrame` function) and then recalculated everything what was changed previously. Thus, setting visible range (either by setting time visible range or logical one) is asynchronous operation and that's why you see previous logical range.

To solve your issue, you can subscribe on [`subscribeVisibleLogicalRangeChange`](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md#subscribevisiblelogicalrangechange) to be notified when visible range is actually changed. Also, see #450.

Let me know if you have any question.
