### ISSUE TITLE
subscribeClick on mobile always get the last index of all the items

### ISSUE THREAD

**Issue by ArcherDs** [tradingview/lightweight-charts#657]
**Lightweight Charts Version:**  3.2.0 

On desktop ，the behavior is perfect
On mobile ,  the param always receive the last index item

https://codesandbox.io/s/blissful-cloud-mucwc?file=/src/index.js

Open  result in new window and use browser's mobile mode can reproduce the problem

#539

**Comment by timocov** [comment]
That's because on touch devices there is "Tracking mode" - you need to long press first to activate crosshair and then you can move crosshair to select a bar.

But I agree that it looks like a bug actually, perhaps we don't need to fire that click event when no tracking mode is active.

Related to #106.

**Comment by timocov** [comment]
Fixed in #972
