### ISSUE TITLE
Custom price lines should be atop of the series

### ISSUE THREAD

**Issue by christose** [tradingview/lightweight-charts#684]
**Lightweight Charts Version:** 

**Steps/code to reproduce:**
By setting a custom price line in the series, it gets override from the series graph.
```
var priceLine = {
      price: 1.21781,
      color: "#ffffff",
      lineWidth: 1,
      lineStyle: LineStyle.Solid,
      axisLabelVisible: true,
    } as PriceLineOptions;

if (this.PriceLine == null) {
        this.PriceLine = this.ChartSeries.createPriceLine(priceLine);
      }
      else {
        this.PriceLine.applyOptions(priceLine);
      }
```

**Actual behavior:**

**Expected behavior:**
The expected behavior is the price line to be on top of any series elements like a candlestick or a line, area etc.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8969889/105521800-0ff65480-5ce5-11eb-8aad-da5be288beab.png)
![image](https://user-images.githubusercontent.com/8969889/105521810-1389db80-5ce5-11eb-9051-3de1b7d6b84f.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment]
Related to https://github.com/tradingview/lightweight-charts/discussions/681

It seems that it's [intended right now](https://github.com/tradingview/lightweight-charts/blob/5e6327f6acaa157a4a3889dae7f71920fa284696/src/model/series.ts#L359-L361), but I think it's strange and we have to change that.

**Comment by gkrasulya** [comment]
Hi. Could you please point out what place in code should be fixed? I may try to create pull request

**Comment by timocov** [comment]
All should be done here is move [this code](https://github.com/tradingview/lightweight-charts/blob/5e6327f6acaa157a4a3889dae7f71920fa284696/src/model/series.ts#L359-L361) after `res.push(this._priceLineView);` line. I think that's it. But please keep in mind that since it's breaking change we cannot merge it in the following 3.4 release so it will wait for 4.0 (which we're planning right after 3.4 if nothing is changed).
