### ISSUE TITLE
Multiple crosshair price labels when there are crosshair markers in series

### ISSUE THREAD

**Issue by devopg** [tradingview/lightweight-charts#686]
**Lightweight Charts Version:** "lightweight-charts": "3.2.0", 

**Steps/code to reproduce:**
i create clear project with last js library version.
value label is not show but time label is okey.
in console no warning/error 
What is can be ? 

```
this.chart = createChart(this.$refs.chartDiv, {
			timeScale: {
				timeVisible: true,
				secondsVisible: true,
			},
			crosshair: {
				horzLine: {
					visible: true,
					labelVisible: true,
				},
				vertLine: {
					visible: true,
					labelVisible: true,
				},
				mode: 1,
			},
		});
this.l= this.chart.addLineSeries({ color: 'green' });
this.l.setData(data);

this.l2= this.chart.addLineSeries({ color: 'red' });
this.l2.setData(data2);

```
![image](https://user-images.githubusercontent.com/61819835/106359081-4e14f900-6321-11eb-8759-1ede02bef325.png)

**Comment by timocov** [comment]
I don't think that we'll implement multiple crosshair price values in lightweight-charts in the future. But let's keep it as a feature request.

**Comment by boskiv** [comment]
I belive this is not about crosshair price. Becaue I have a similar issue:
![Screen Shot 2021-07-25 at 12 39 06 PM](https://user-images.githubusercontent.com/1939783/126911828-d019de1a-d351-4136-862d-100d3d911254.png)

**Comment by prirefi** [comment]
Any update or new developments on this feature?

**Comment by timocov** [comment]
Anyone in the thread and @prirefi @boskiv @devopg especially - what would you expect as a solution here? How in your opinion it should be solved?

**Comment by boskiv** [comment]
I expect to see labels on price scale when I move mouse over graph. 1 version can show all labels from indicators and chart. 2 version can be configurable what to show and what to hide.

**Comment by timocov** [comment]
@boskiv So you want to have 2 crosshair labels - 1 for the crosshair itself and another ones for a dot, i.e. a series value for this time, am I right?

**Comment by boskiv** [comment]
@timocov As you can see from my recent screenshot there is no labels on price scale from chart and indicator(MA). I want to see all labels from all objects that fit under crosshair

**Comment by timocov** [comment]
> is no labels on price scale from chart and indicator(MA). 

Are you talking about labels for the latest price or for crosshair? Because it seems that you disable last price labels. I just don't want to mix them together to avoid any confusion. For me it is still unclear what and why you want to get it so that's why I'm asking questions.

**Comment by SlicedSilver** [comment]
Thank you for your feature request for Lightweight Charts. In order to keep the library lightweight and maintain a narrow focus, we strive to include only strictly required features in the core library. As a result, we have decided that this requested feature should be implemented as a plugin instead, and will be closing this issue as a result.

We recently introduced the ability to write plugins for Lightweight Charts, allowing users like you to extend the functionality of the library without adding it to the core. We highly recommend implementing your feature request as a plugin to achieve the desired functionality while keeping the core bundle size smaller for all users.

To get started with plugins, please refer to our [Plugins Documentation](https://tradingview.github.io/lightweight-charts/docs/plugins/intro) for a better understanding of what is possible and how plugins work. You can also explore our collection of [plugin examples](https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples) (with a [preview hosted here](https://tradingview.github.io/lightweight-charts/plugin-examples/)) for inspiration and guidance on implementing specific functionality.

For your particular feature request, we suggest taking a look at the following examples (see above links):
- Partial Price Line
- User Defined Price Lines
- User Price Alerts

To help you get started quickly, we have created an NPM package called [create-lwc-plugin](https://www.npmjs.com/package/create-lwc-plugin), which sets up a plugin project for you. This way, you can hit the ground running with your plugin development.

If you do create a plugin based on your feature request, we would appreciate it if you could publish it on GitHub or NPM and let us know. This way, we can share it with the rest of the community. It would be helpful if you could prefix your NPM package name with `lwc-plugin-` for easier discoverability by others.

Thank you for your understanding and support. We believe implementing your feature request as a plugin will greatly benefit both you and the Lightweight Charts community.
