### ISSUE TITLE
Vertical lines on candlestick chart vs line chart - it's not straight on candlestick chart

### ISSUE THREAD

**Issue by pavitrakumar78** [tradingview/lightweight-charts#698]
**Lightweight Charts Version:** 3.2.0

**Steps/code to reproduce:**

Candlestick chart: https://jsfiddle.net/pavitrakumar/qr2htzv9/
Line chart: https://jsfiddle.net/pavitrakumar/36kowhuq/
All I've done is, add
```
	var series2 = chart.addLineSeries({
		color: 'rgb(45, 120, 255)',
		lineWidth: 2,
	});
	var data2 = [
          {time: { year: 2018 ,month: 4 ,day: 18 }, value: 999},
          {time: { year: 2018 ,month: 4 ,day: 18 }, value: -999}
    ]
  series2.setData(data2);
```
to the example fiddles for candlestick and line chart.

please zoon on the y-axis.

**Actual behavior:**

The vertical line on candlestick is not straight - it's diagonal.

**Expected behavior:**

The vertical line on candlestick chart needs to be straight.

**Screenshots:**

![image](https://user-images.githubusercontent.com/5354407/107568357-e017de00-6c0c-11eb-84ed-2300f0181148.png)

![image](https://user-images.githubusercontent.com/5354407/107568385-e908af80-6c0c-11eb-8949-d0bcd8b7cf3e.png)

**CodeSandbox/JSFiddle/etc link:**

Candlestick chart: https://jsfiddle.net/pavitrakumar/qr2htzv9/
Line chart: https://jsfiddle.net/pavitrakumar/36kowhuq/

**Comment by timocov** [comment]
> All I've done is, add

Is that intended that for candlestick charts you have 2019 instead of 2018 for that line?

But anyway, I don't think that we'll support such thing like having in the data 2 items with the same time. If you enable "development" build instead of production one you'll an error like `Assertion failed: data must be asc ordered by time, index=1, time=1524009600, prev time=1524009600`. The fact that at the time it may work isn't intended and might be broken in the future.

**Comment by pavitrakumar78** [comment]
Is there any other way to add vertical lines? to candlestick/line charts?

**Comment by timocov** [comment]
> Is there any other way to add vertical lines? to candlestick/line charts?

No, I don't think there is a way to do this at the time. We don't plan to add drawings though. Probably we'll provide an API to draw on the canvas from your code, but I believe it's far away from an implementation right now.
