### ISSUE TITLE
[bug] axis not showing correctly Brave browser

### ISSUE THREAD

**Issue by Alex-CodeLab** [tradingview/lightweight-charts#85]
**Lightweight Charts Version:**  1.0.0 rc5
Ubuntu 18.04, Brave 0.65.118 

**Steps/code to reproduce:**
Charts only show part of the axis on Brave browser.
For example, all examples (like https://jsfiddle.net/TradingView/61xkszjp/ )

![Screenshot from 2019-06-21 10-50-52](https://user-images.githubusercontent.com/1678423/59915166-463e6480-941c-11e9-904f-1ee758999bb3.png)
![Screenshot from 2019-06-21 12-06-11](https://user-images.githubusercontent.com/1678423/59915499-1348a080-941d-11e9-866e-9bb111db4816.png)

**Comment by subzey** [comment]
Brave Browser strikes again :grinning: 

Width of the text labels should be measured first in order to get the correct price axis width. Brave assumes `CanvasContext2D::measureText()` a [fingerprinting technique](https://github.com/brave/brave-browser/issues/1738).

It really can be used for fingerprinting as `measureText` returns a value with prcecision up to 4..5 digits in the fractional part that may differ subtly between computers. The expected workaround would be just rounding the width lowering the precision of this measurement and making the fingerprinting unusable.

But no. They always return `0` for any input.

**Comment by timocov** [comment]
@awunder can you please provide a little repro with data you have on the chart which we can open in Brave browser to investigate the latest problem (quite possible that it has the same reason with the previous one, but let's try).

**Comment by timocov** [comment]
I'm going to close this issue. If you'll have any updates - feel free to reopen it.
