### ISSUE TITLE
The chart is blank on printed page in Chromium (Ctrl+P)

### ISSUE THREAD

**Issue by dtanp-rft** [tradingview/lightweight-charts#873]
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**
- Go to demo page https://www.tradingview.com/lightweight-charts/
- Ctrl + P in Chrome to print the page
- Observe print preview

**Actual behavior:**

None of the chart is printed. It's blank canvas.

**Expected behavior:**

It should be printed

Note:
- Firefox, Safari works fine
- It seems that only little square on the bottom right is printed
- Same issue with r-click on chart canvas and save image

**Comment by timocov** [comment]
> Same issue with r-click on chart canvas and save image

That's because due performance optimizations we're creating several canvases for panes/price axis/time axis. If you want to get an image of chart, please use `takeScreenshot` function instead.

> Firefox, Safari works fine

Doesn't it mean that this is a bug in Chromium? 🤔

**Comment by timocov** [comment]
If someone wants to investigate this and create an issue in chromium - you're more than welcomed to do it (or find a workaround for the library).

**Comment by subzey** [comment]
I believe the reason is that when being printed the page is briefly switched to the `media: print`.

![image](https://user-images.githubusercontent.com/810582/140080752-7b0f8f9f-60c6-4636-a09b-18837295f05f.png)

And in this mode the `window.devicePixelRatio` and the `(resolution)` media doesn't match anymore. _Looks like the media reflects the printer pixel density and the `window.devicePixelRatio` is the screen pixel density._

The workaround could be not changing the canvas size in the fancy-canvas if the `window.devicePixelRatio` hasn't really changed.

**Comment by timocov** [comment]
Thanks @subzey! It seems that the first fix should be done in https://github.com/tradingview/fancy-canvas/ package. @Nipheris fyi

**Comment by keithlfs** [comment]
That PR merge is still pending as of Sept '22 😬

Would be great to be able to print charts properly, this bug affects also affects chart PDF rendering when using Puppeteersharp/Chromium.
