### ISSUE TITLE
belowBar/aboveBar render wrong

### ISSUE THREAD

**Issue by boskiv** [tradingview/lightweight-charts#925]
**Lightweight Charts Version:** 
3.7.0
**Steps/code to reproduce:**

[Codesandbox](https://codesandbox.io/s/suspicious-mopsa-zovxe?file=/src/components/Chart.vue)
**Actual behavior:**

belowBar renders wrong place
![Screen Shot 2021-12-02 at 22 12 46](https://user-images.githubusercontent.com/1939783/144544907-bb8a2744-5355-44a0-9e7b-d4a2f181e618.png)

**Comment by timocov** [comment]
The issue is with your data. For some reason in your data sometimes high < low, which is not correct:

![image](https://user-images.githubusercontent.com/3112183/144577923-6ce403b2-76e3-4c80-82ca-c2de5b6c2867.png)

I added this code to check it.

```js
const lastBar = cdata_price[cdata_price.length - 1];
if (lastBar.high < lastBar.low) {
    console.warn(`low=${lastBar.low} high=${lastBar.high}`);
}
```

Probably we need to extend [this checks](https://github.com/tradingview/lightweight-charts/blob/f8b7d306aa8fc350696db6a280cc4b7f9ee794ec/src/api/data-validators.ts#L66-L85)...

**Comment by boskiv** [comment]
@timocov  is there an option to draw marker at specific price level that i can set myself? Because this is spread chart and ohlc candles is synthetic there.

**Comment by timocov** [comment]
>  is there an option to draw marker at specific price level that i can set myself?

See #127

> Because this is spread chart and ohlc candles is synthetic there.

But this bars are incorrect, it is impossible to have high < low, this is incorrect interpreting of bars I'd say. I believe this is not the only issue you might see on the chart. Another one could be incorrect autoscaling for instance. And probably much more, because the library relies on the data.
